In [1]:
for x in ARGS; println(x); end

/Users/utensil/Library/Jupyter/runtime/kernel-28d6ca25-a548-4761-a6ed-7b0076c765b8.json


In [2]:
println("Greetings! 你好! 안녕하세요?")

Greetings! 你好! 안녕하세요?


In [3]:
run(`julia --help`)

julia [switches] -- [programfile] [args...]
 -v, --version             Display version information
 -h, --help                Print this message

 -J, --sysimage <file>     Start up with the given system image file
 --precompiled={yes|no}    Use precompiled code from system image if available
 -H, --home <dir>          Set location of julia executable
 --startup-file={yes|no}   Load ~/.juliarc.jl
 -f, --no-startup          Don't load ~/.juliarc (deprecated, use --startup-file=no)
 -F                        Load ~/.juliarc (deprecated, use --startup-file=yes)
 --handle-signals={yes|no} Enable or disable Julia's default signal handlers

 -e, --eval <expr>         Evaluate <expr>
 -E, --print <expr>        Evaluate and show <expr>
 -P, --post-boot <expr>    Evaluate <expr>, but don't disable interactive mode (deprecated, use -i -e instead)
 -L, --load <file>         Load <file> immediately on all processors

 -p, --procs {N|auto}      Integer value N launches N additional local worker pro

In [4]:
理念="idea"

"idea"

In [6]:
println("$理念")

idea


In [7]:
π

π = 3.1415926535897...

From __Variables: Stylistic Conventions__

While Julia imposes few restrictions on valid names, it has become useful to adopt the following conventions:

* Names of variables are in lower case.
* Word separation can be indicated by underscores (`'_'`), but use of underscores is discouraged unless the name would be hard to read otherwise.
* Names of `Type`s and `Module`s begin with a capital letter and word separation is shown with upper camel case instead of underscores.
* Names of `function`s and `macro`s are in lower case, without underscores.
* Functions that write to their arguments have names that end in `!`. These are sometimes called “mutating” or “in-place” functions because they are intended to produce changes in their arguments after the function is called, not just return a value.

In [9]:
WORD_SIZE

64

In [10]:
UInt

UInt64

In [11]:
typeof(WORD_SIZE)

Int64

In [12]:
typeof(π)

Irrational{:π}

In [13]:
0b10

0x02

In [14]:
0o10

0x08

In [15]:
for T in [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128]
    println("$(lpad(T,7)): [$(typemin(T)),$(typemax(T))]")
end

   Int8: [-128,127]
  Int16: [-32768,32767]
  Int32: [-2147483648,2147483647]
  Int64: [-9223372036854775808,9223372036854775807]
 Int128: [-170141183460469231731687303715884105728,170141183460469231731687303715884105727]
  UInt8: [0,255]
 UInt16: [0,65535]
 UInt32: [0,4294967295]
 UInt64: [0,18446744073709551615]
UInt128: [0,340282366920938463463374607431768211455]


In [17]:
typemax(Int64) + 1 == typemin(Int64)

true

In [18]:
typemax(UInt64) + 1 == typemin(UInt64)

true

In [19]:
div(typemax(Int64), 0)

LoadError: LoadError: DivideError: integer division error
while loading In[19], in expression starting on line 1

In [21]:
@printf "%ld" typemin(Int64)
div(typemin(Int64), -1)

-9223372036854775808

LoadError: LoadError: DivideError: integer division error
while loading In[21], in expression starting on line 2

In [37]:
0x.1p0 == (1.0/16.0)

true

In [43]:
0x.1p1 == (1.0/16.0) * 2^1

true

In [44]:
sizeof(0x.1p0)

8

In [45]:
1/Inf

0.0

In [46]:
sizeof(Inf)

8

In [47]:
0/0

NaN

In [48]:
2 * Inf

Inf

In [49]:
Inf^Inf

Inf

In [51]:
Inf / Inf

NaN

In [52]:
0 * Inf

NaN

In [53]:
(typemin(Float64),typemax(Float64))

(-Inf,Inf)

In [56]:
eps(Float32),eps(Float64), eps(Float32) / eps(Float64)

(1.1920929f-7,2.220446049250313e-16,5.36870912e8)

In [57]:
nextfloat(π)

LoadError: LoadError: MethodError: `nextfloat` has no method matching nextfloat(::Irrational{:π})
while loading In[57], in expression starting on line 1

In [58]:
nextfloat(3.141592653)

3.1415926530000005

In [59]:
1.1 + 0.1

1.2000000000000002

In [60]:
with_rounding(Float64,RoundDown) do
    1.1 + 0.1
end

1.2

In [61]:
1.1 + 0.1 == with_rounding(Float64,RoundDown) do
    1.1 + 0.1
end

false

In [1]:
BigInt(typemax(Int64))*BigInt(12345678)

113868781241213194875412146

In [2]:
parse(BigFloat, "1.23456789012345678901")

1.234567890123456789010000000000000000000000000000000000000000000000000000000004

In [3]:
BigFloat(π)

3.141592653589793238462643383279502884197169399375105820974944592307816406286198

In [7]:
factorial(BigInt(40))

815915283247897734345611269596115894272000000000

In [8]:
@doc factorial

```rst
..  factorial(n,k)

Compute ``factorial(n)/factorial(k)``
```

```rst
..  factorial(n)

Factorial of ``n``.  If ``n`` is an :obj:`Integer`, the factorial
is computed as an integer (promoted to at least 64 bits).  Note
that this may overflow if ``n`` is not small, but you can use
``factorial(big(n))`` to compute the result exactly in arbitrary
precision.  If ``n`` is not an ``Integer``, ``factorial(n)`` is
equivalent to :func:`gamma(n+1) <gamma>`.
```


In [9]:
x = 3

3

In [10]:
2x^2 - 3x + 1

10

In [11]:
1.5x^2 - .5x + 1

13.0

In [12]:
2^2x

64

In [13]:
(2^2)x

12

In [47]:
print_type_info(T) = begin
    const COLUME_WIDTH = 20
    # TODO %s can't preserve literal
    @printf "%s:\n" T
    @printf "\t%s\t%s\n" rpad("zero:",COLUME_WIDTH) zero(T)
    @printf "\t%s\t%s\n" rpad("one:",COLUME_WIDTH) one(T)
    try
        @printf "\t%s\t%s\n" rpad("typemin:",COLUME_WIDTH) typemin(T)
        @printf "\t%s\t%s\n" rpad("typemax:",COLUME_WIDTH) typemax(T)
    catch e
        # do nothing
    end
end
    
for t in [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128,BigInt]
    print_type_info(t)
end
for t in [Float16,Float32,Float64,BigFloat]
    print_type_info(t)
end

Int8:
	zero:               	0
	one:                	1
	typemin:            	-128
	typemax:            	127
Int16:
	zero:               	0
	one:                	1
	typemin:            	-32768
	typemax:            	32767
Int32:
	zero:               	0
	one:                	1
	typemin:            	-2147483648
	typemax:            	2147483647
Int64:
	zero:               	0
	one:                	1
	typemin:            	-9223372036854775808
	typemax:            	9223372036854775807
Int128:
	zero:               	0
	one:                	1
	typemin:            	-170141183460469231731687303715884105728
	typemax:            	170141183460469231731687303715884105727
UInt8:
	zero:               	0
	one:                	1
	typemin:            	0
	typemax:            	255
UInt16:
	zero:               	0
	one:                	1
	typemin:            	0
	typemax:            	65535
UInt32:
	zero:               	0
	one:                	1
	typemin:            	0
	typemax:            	4294967295
UInt64:
	zer

In [48]:
one(Float32)

1.0f0

In [50]:
one(Float64)

1.0

In [51]:
1 / 2

0.5

In [52]:
typeof(1 / 2)

Float64

In [53]:
2 \ 1

0.5

In [54]:
100 % 33

1

In [58]:
bits(~0b1010101010101010)

"0101010101010101"

In [59]:
bits(0b11 & 0b10)

"00000010"

In [60]:
bits(0b11 | 0b10)

"00000011"

In [63]:
bits(0b1010 $ 0b1100) # xor

"00000110"

In [65]:
1 >> 2 == 1 >>> 2 # TODO what's the difference?

true

In [66]:
isequal(1 >> 2, 1 >>> 2)

true

In [67]:
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 < 3 != 5

true

In [68]:
Float32(π)

3.1415927f0

In [69]:
Float64(π)

3.141592653589793

In [71]:
cos(1 + 2im) == cos(complex(1, 2))

true

In [72]:
complex(Inf, NaN)

Inf + NaN*im

In [73]:
typeof(2//3)

Rational{Int64}

In [74]:
0.33 < 1//3

true

In [75]:
str = "Hello, world.\n"

"Hello, world.\n"

In [76]:
str[end]

'\n'

In [77]:
str[end÷2]

' '

In [78]:
str[end÷3]

'l'

In [79]:
str[end÷3:end÷2]

"lo, "

In [80]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [81]:
for i = 1:endof(s)
    try
        println(s[i])
    catch
        # ignore the index error
    end
end

∀
 
x
 
∃
 
y


In [82]:
for c in s
    println(c)
end

∀
 
x
 
∃
 
y


In [85]:
language="Julia"
"Hello $language\!" == string("Hello ", language, "!")

true

In [86]:
"1 + 2 = $(1 + 2)"

"1 + 2 = 3"

In [88]:
str = """
   Hello,
   $language.
 """

"  Hello,\n  Julia.\n"

In [1]:
last_index = -1
while last_index != 0
    last_index = last_index < 0 ? search("xylophone", 'o') : search("xylophone", 'o', last_index + 1)
    @printf "%d\n" last_index
end

4
7
0


In [2]:
repeat(".:Z:.", 10)

".:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:."

In [4]:
join(["apples", "bananas", "pear", "pineapples"], ", ", " and ")

"apples, bananas, pear and pineapples"

In [8]:
regex = r"^\s*(?:#|$)"

r"^\s*(?:#|$)"

In [9]:
ismatch(regex, "not a comment")

false

In [10]:
ismatch(regex, "# a comment")

true

In [11]:
typeof(regex)

Regex

In [14]:
m = match(r"^\s*(?:#\s*(.*?)\s*$|$)", "# a comment")

RegexMatch("# a comment", 1="a comment")

In [15]:
m[1]

"a comment"

In [16]:
m.match

"# a comment"

In [17]:
m.captures

1-element Array{Union{SubString{UTF8String},Void},1}:
 "a comment"

In [18]:
m.offsets

1-element Array{Int64,1}:
 3

In [27]:
replace("first second third", r"^(\w+) (?P<agroup>\w+)", s"\g<agroup> \1")

"second first third"

In [28]:
replace("first second third", r"(\w+) (?P<agroup>\w+)$", s"\g<agroup> \1")

"first third second"

In [29]:
b"DATA\xff\u2200"

8-element Array{UInt8,1}:
 0x44
 0x41
 0x54
 0x41
 0xff
 0xe2
 0x88
 0x80

In [31]:
bits('\u2200')

"00000000000000000010001000000000"

In [33]:
bits('\xe2\x88\x80')

"00000000000000000010001000000000"

In [38]:
function f(x,y)
  x + y
end
 ∑ = f

f (generic function with 1 method)

In [39]:
f(2, 3) ==  ∑(2, 3)

true

In [40]:
function hypot(x,y)
  x = abs(x)
  y = abs(y)
  if x > y
    r = y/x
    return x*sqrt(1+r*r)
  end
  if y == 0
    return zero(x)
  end
  r = x/y
  return y*sqrt(1+r*r)
end

hypot (generic function with 1 method)

In [41]:
hypot(3, 4)

5.0

In [42]:
+(1,2,3)

6

In [43]:
fadd = +
fadd(1, 2, 3)

6

In [45]:
[1 2 3]

1x3 Array{Int64,2}:
 1  2  3

In [46]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [47]:
[1 2; 3 4; 5 6]

3x2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [48]:
hcat(1, 2, 3) == [1 2 3]

true

In [49]:
vcat(1, 2, 3) == [1, 2, 3]

true

In [58]:
hvcat( (2, 2, 2) , 1, 2, 3, 4, 5, 6) == [1 2; 3 4; 5 6]

true

In [66]:
hvcat(2, 1, 2, 3, 4, 5, 6) == [1 2; 3 4; 5 6]

true

In [71]:
mx = [1 2im; 3im 4; 5 6im]

3x2 Array{Complex{Int64},2}:
 1+0im  0+2im
 0+3im  4+0im
 5+0im  0+6im

In [72]:
mx'

2x3 Array{Complex{Int64},2}:
 1+0im  0-3im  5+0im
 0-2im  4+0im  0-6im

In [73]:
mx.'

2x3 Array{Complex{Int64},2}:
 1+0im  0+3im  5+0im
 0+2im  4+0im  0+6im

In [75]:
1:100 == colon(1, 100)

true

In [76]:
# See Functions: Operators With Special Names

In [77]:
x -> x^2 + 2x - 1

(anonymous function)

In [78]:
function (x)
   x^2 + 2x - 1
end

(anonymous function)

In [79]:
map(x -> x^2 + 2x - 1, [1,3,-1])

3-element Array{Int64,1}:
  2
 14
 -2

In [80]:
function foo(a,b)
    a+b, a*b
end
foo(2, 3)

(5,6)

In [81]:
bar(a,b,x...) = (a,b,x)
bar(1,2,3,4,5,6)

(1,2,(3,4,5,6))

In [82]:
baz(a,b) = a + b
args = [1,2]
baz(args...)

3

In [86]:
function bonus_add(a, b, c=5)
    a + b + c
end
bonus_add(2, 3) == bonus_add(2, 3, 5)

true

In [91]:
function extra_add(a; b=3, c=5)
    a + b + c
end
extra_add(2, b=4, c=4) == extra_add(0, b=5) == extra_add(2)

true

In [95]:
map(x->begin
           if x < 0 && iseven(x)
               return 0
           elseif x == 0
               return 1
           else
               return x
           end
       end,
[1, 2, 3]) == map([1, 2, 3]) do x # Am I writing ruby? ^_^
    if x < 0 && iseven(x)
        return 0
    elseif x == 0
        return 1
    else
        return x
    end
end # The do x syntax creates an anonymous function with argument x and passes it as the first argument

true

In [101]:
begin
    x = 1
    y = 2
    x + y
end == (x = 1; y = 2; x + y)

true

In [102]:
# Although it is typical, there is no requirement that begin blocks be multiline or that (;) chains be single-line
begin x = 1; y = 2; x + y end == (x = 1;
        y = 2;
        x + y)

true

In [105]:
function test_order(x, y)
 if x < y
   println("$x is less than $y")
 elseif x > y
   println("$x is greater than $y")
 else
   println("$x is equal to $y")
 end
end

test_order (generic function with 1 method)

In [106]:
test_order(1, 3)

1 is less than 3


`if` blocks are “leaky”, i.e. they do not introduce a local scope. This means that new variables defined inside the `ìf` clauses can be used after the `if` block, even if they weren’t defined before. 

In [107]:
function test_order_leaky(x,y)
 if x < y
   relation = "less than"
 elseif x == y
   relation = "equal to"
 end
 println("$x is ", relation, " $y.")
end

test_order_leaky (generic function with 1 method)

In [110]:
test_order_leaky(1, 3)

1 is less than 3.


In [111]:
test_order_leaky(11, 3)

LoadError: LoadError: UndefVarError: relation not defined
while loading In[111], in expression starting on line 1

In [112]:
5 > 1 && println("5 > 1")

5 > 1


In [113]:
4 < 1 || println("false")

false


In [114]:
i = 1
while i <= 5
 println(i)
 i += 1
end

1
2
3
4
5


In [116]:
for j=1:5; println(j); end

1
2
3
4
5


In [117]:
for s in ["foo","bar","baz"]
 println(s)
end

foo
bar
baz


In [119]:
# OH! This is AWESOME!
for i = 1:2, j in ["apple", "banana", "pear"]
 println((i, j))
end

(1,"apple")
(1,"banana")
(1,"pear")
(2,"apple")
(2,"banana")
(2,"pear")


In [120]:
positive_exp(x) = x>=0 ? exp(-x) : throw(DomainError())

positive_exp (generic function with 1 method)

In [121]:
positive_exp(1)

0.36787944117144233

In [122]:
positive_exp(-100)

LoadError: LoadError: DomainError:
while loading In[122], in expression starting on line 1

In [123]:
typeof(DomainError()) <: Exception

true

In [125]:
throw(UndefVarError(:a_missing_variable))

LoadError: LoadError: UndefVarError: a_missing_variable not defined
while loading In[125], in expression starting on line 1

In [126]:
fussy_sqrt(x) = x >= 0 ? sqrt(x) : error("negative x not allowed")

fussy_sqrt (generic function with 1 method)

In [127]:
fussy_sqrt(100)

10.0

In [128]:
fussy_sqrt(-250)

LoadError: LoadError: negative x not allowed
while loading In[128], in expression starting on line 1

In [129]:
function verbose_fussy_sqrt(x)
 println("before fussy_sqrt")
 r = fussy_sqrt(x)
 println("after fussy_sqrt")
 return r
end

verbose_fussy_sqrt (generic function with 1 method)

In [130]:
verbose_fussy_sqrt(-1)

before fussy_sqrt


LoadError: LoadError: negative x not allowed
while loading In[130], in expression starting on line 1

In [131]:
info("Hi"); 1+1
warn("Hi"); 1+1
error("Hi"); 1+1

INFO: Hi


LoadError: LoadError: Hi
while loading In[131], in expression starting on line 3

In [132]:
 try error() end #Returns nothing

In [133]:
try
    println("step 1 ok")
    error("step 2 failed")
    println("step 3 was never reached")
catch e
    if isa(e, DomainError)
        # Obviously, it's not
    else
        println(e)
    end
finally
    println("step 4 is ensured")
end
    

step 1 ok
ErrorException("step 2 failed")
step 4 is ensured
