In [1]:
for x in ARGS; println(x); end

/Users/utensil/Library/Jupyter/runtime/kernel-28d6ca25-a548-4761-a6ed-7b0076c765b8.json


In [2]:
println("Greetings! 你好! 안녕하세요?")

Greetings! 你好! 안녕하세요?


In [3]:
run(`julia --help`)

julia [switches] -- [programfile] [args...]
 -v, --version             Display version information
 -h, --help                Print this message

 -J, --sysimage <file>     Start up with the given system image file
 --precompiled={yes|no}    Use precompiled code from system image if available
 -H, --home <dir>          Set location of julia executable
 --startup-file={yes|no}   Load ~/.juliarc.jl
 -f, --no-startup          Don't load ~/.juliarc (deprecated, use --startup-file=no)
 -F                        Load ~/.juliarc (deprecated, use --startup-file=yes)
 --handle-signals={yes|no} Enable or disable Julia's default signal handlers

 -e, --eval <expr>         Evaluate <expr>
 -E, --print <expr>        Evaluate and show <expr>
 -P, --post-boot <expr>    Evaluate <expr>, but don't disable interactive mode (deprecated, use -i -e instead)
 -L, --load <file>         Load <file> immediately on all processors

 -p, --procs {N|auto}      Integer value N launches N additional local worker pro

In [4]:
理念="idea"

"idea"

In [6]:
println("$理念")

idea


In [7]:
π

π = 3.1415926535897...

From __Variables: Stylistic Conventions__

While Julia imposes few restrictions on valid names, it has become useful to adopt the following conventions:

* Names of variables are in lower case.
* Word separation can be indicated by underscores (`'_'`), but use of underscores is discouraged unless the name would be hard to read otherwise.
* Names of `Type`s and `Module`s begin with a capital letter and word separation is shown with upper camel case instead of underscores.
* Names of `function`s and `macro`s are in lower case, without underscores.
* Functions that write to their arguments have names that end in `!`. These are sometimes called “mutating” or “in-place” functions because they are intended to produce changes in their arguments after the function is called, not just return a value.

In [9]:
WORD_SIZE

64

In [10]:
UInt

UInt64

In [11]:
typeof(WORD_SIZE)

Int64

In [12]:
typeof(π)

Irrational{:π}

In [13]:
0b10

0x02

In [14]:
0o10

0x08

In [15]:
for T in [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128]
    println("$(lpad(T,7)): [$(typemin(T)),$(typemax(T))]")
end

   Int8: [-128,127]
  Int16: [-32768,32767]
  Int32: [-2147483648,2147483647]
  Int64: [-9223372036854775808,9223372036854775807]
 Int128: [-170141183460469231731687303715884105728,170141183460469231731687303715884105727]
  UInt8: [0,255]
 UInt16: [0,65535]
 UInt32: [0,4294967295]
 UInt64: [0,18446744073709551615]
UInt128: [0,340282366920938463463374607431768211455]


In [17]:
typemax(Int64) + 1 == typemin(Int64)

true

In [18]:
typemax(UInt64) + 1 == typemin(UInt64)

true

In [19]:
div(typemax(Int64), 0)

LoadError: LoadError: DivideError: integer division error
while loading In[19], in expression starting on line 1

In [21]:
@printf "%ld" typemin(Int64)
div(typemin(Int64), -1)

-9223372036854775808

LoadError: LoadError: DivideError: integer division error
while loading In[21], in expression starting on line 2

In [37]:
0x.1p0 == (1.0/16.0)

true

In [43]:
0x.1p1 == (1.0/16.0) * 2^1

true

In [44]:
sizeof(0x.1p0)

8

In [45]:
1/Inf

0.0

In [46]:
sizeof(Inf)

8

In [47]:
0/0

NaN

In [48]:
2 * Inf

Inf

In [49]:
Inf^Inf

Inf

In [51]:
Inf / Inf

NaN

In [52]:
0 * Inf

NaN

In [53]:
(typemin(Float64),typemax(Float64))

(-Inf,Inf)

In [56]:
eps(Float32),eps(Float64), eps(Float32) / eps(Float64)

(1.1920929f-7,2.220446049250313e-16,5.36870912e8)

In [57]:
nextfloat(π)

LoadError: LoadError: MethodError: `nextfloat` has no method matching nextfloat(::Irrational{:π})
while loading In[57], in expression starting on line 1

In [58]:
nextfloat(3.141592653)

3.1415926530000005

In [59]:
1.1 + 0.1

1.2000000000000002

In [60]:
with_rounding(Float64,RoundDown) do
    1.1 + 0.1
end

1.2

In [61]:
1.1 + 0.1 == with_rounding(Float64,RoundDown) do
    1.1 + 0.1
end

false

In [1]:
BigInt(typemax(Int64))*BigInt(12345678)

113868781241213194875412146

In [2]:
parse(BigFloat, "1.23456789012345678901")

1.234567890123456789010000000000000000000000000000000000000000000000000000000004

In [3]:
BigFloat(π)

3.141592653589793238462643383279502884197169399375105820974944592307816406286198

In [7]:
factorial(BigInt(40))

815915283247897734345611269596115894272000000000

In [8]:
@doc factorial

```rst
..  factorial(n,k)

Compute ``factorial(n)/factorial(k)``
```

```rst
..  factorial(n)

Factorial of ``n``.  If ``n`` is an :obj:`Integer`, the factorial
is computed as an integer (promoted to at least 64 bits).  Note
that this may overflow if ``n`` is not small, but you can use
``factorial(big(n))`` to compute the result exactly in arbitrary
precision.  If ``n`` is not an ``Integer``, ``factorial(n)`` is
equivalent to :func:`gamma(n+1) <gamma>`.
```


In [9]:
x = 3

3

In [10]:
2x^2 - 3x + 1

10

In [11]:
1.5x^2 - .5x + 1

13.0

In [12]:
2^2x

64

In [13]:
(2^2)x

12

In [47]:
print_type_info(T) = begin
    const COLUME_WIDTH = 20
    # TODO %s can't preserve literal
    @printf "%s:\n" T
    @printf "\t%s\t%s\n" rpad("zero:",COLUME_WIDTH) zero(T)
    @printf "\t%s\t%s\n" rpad("one:",COLUME_WIDTH) one(T)
    try
        @printf "\t%s\t%s\n" rpad("typemin:",COLUME_WIDTH) typemin(T)
        @printf "\t%s\t%s\n" rpad("typemax:",COLUME_WIDTH) typemax(T)
    catch e
        # do nothing
    end
end
    
for t in [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128,BigInt]
    print_type_info(t)
end
for t in [Float16,Float32,Float64,BigFloat]
    print_type_info(t)
end

Int8:
	zero:               	0
	one:                	1
	typemin:            	-128
	typemax:            	127
Int16:
	zero:               	0
	one:                	1
	typemin:            	-32768
	typemax:            	32767
Int32:
	zero:               	0
	one:                	1
	typemin:            	-2147483648
	typemax:            	2147483647
Int64:
	zero:               	0
	one:                	1
	typemin:            	-9223372036854775808
	typemax:            	9223372036854775807
Int128:
	zero:               	0
	one:                	1
	typemin:            	-170141183460469231731687303715884105728
	typemax:            	170141183460469231731687303715884105727
UInt8:
	zero:               	0
	one:                	1
	typemin:            	0
	typemax:            	255
UInt16:
	zero:               	0
	one:                	1
	typemin:            	0
	typemax:            	65535
UInt32:
	zero:               	0
	one:                	1
	typemin:            	0
	typemax:            	4294967295
UInt64:
	zer

In [48]:
one(Float32)

1.0f0

In [50]:
one(Float64)

1.0

In [51]:
1 / 2

0.5

In [52]:
typeof(1 / 2)

Float64

In [53]:
2 \ 1

0.5

In [54]:
100 % 33

1

In [58]:
bits(~0b1010101010101010)

"0101010101010101"

In [59]:
bits(0b11 & 0b10)

"00000010"

In [60]:
bits(0b11 | 0b10)

"00000011"

In [63]:
bits(0b1010 $ 0b1100) # xor

"00000110"

In [65]:
1 >> 2 == 1 >>> 2 # TODO what's the difference?

true

In [66]:
isequal(1 >> 2, 1 >>> 2)

true

In [67]:
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 < 3 != 5

true

In [68]:
Float32(π)

3.1415927f0

In [69]:
Float64(π)

3.141592653589793

In [71]:
cos(1 + 2im) == cos(complex(1, 2))

true

In [72]:
complex(Inf, NaN)

Inf + NaN*im

In [73]:
typeof(2//3)

Rational{Int64}

In [74]:
0.33 < 1//3

true

In [75]:
str = "Hello, world.\n"

"Hello, world.\n"

In [76]:
str[end]

'\n'

In [77]:
str[end÷2]

' '

In [78]:
str[end÷3]

'l'

In [79]:
str[end÷3:end÷2]

"lo, "

In [80]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [81]:
for i = 1:endof(s)
    try
        println(s[i])
    catch
        # ignore the index error
    end
end

∀
 
x
 
∃
 
y


In [82]:
for c in s
    println(c)
end

∀
 
x
 
∃
 
y


In [85]:
language="Julia"
"Hello $language\!" == string("Hello ", language, "!")

true

In [86]:
"1 + 2 = $(1 + 2)"

"1 + 2 = 3"

In [88]:
str = """
   Hello,
   $language.
 """

"  Hello,\n  Julia.\n"

In [1]:
last_index = -1
while last_index != 0
    last_index = last_index < 0 ? search("xylophone", 'o') : search("xylophone", 'o', last_index + 1)
    @printf "%d\n" last_index
end

4
7
0


In [2]:
repeat(".:Z:.", 10)

".:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:."

In [4]:
join(["apples", "bananas", "pear", "pineapples"], ", ", " and ")

"apples, bananas, pear and pineapples"

In [8]:
regex = r"^\s*(?:#|$)"

r"^\s*(?:#|$)"

In [9]:
ismatch(regex, "not a comment")

false

In [10]:
ismatch(regex, "# a comment")

true

In [11]:
typeof(regex)

Regex

In [14]:
m = match(r"^\s*(?:#\s*(.*?)\s*$|$)", "# a comment")

RegexMatch("# a comment", 1="a comment")

In [15]:
m[1]

"a comment"

In [16]:
m.match

"# a comment"

In [17]:
m.captures

1-element Array{Union{SubString{UTF8String},Void},1}:
 "a comment"

In [18]:
m.offsets

1-element Array{Int64,1}:
 3

In [27]:
replace("first second third", r"^(\w+) (?P<agroup>\w+)", s"\g<agroup> \1")

"second first third"

In [28]:
replace("first second third", r"(\w+) (?P<agroup>\w+)$", s"\g<agroup> \1")

"first third second"

In [29]:
b"DATA\xff\u2200"

8-element Array{UInt8,1}:
 0x44
 0x41
 0x54
 0x41
 0xff
 0xe2
 0x88
 0x80

In [31]:
bits('\u2200')

"00000000000000000010001000000000"

In [33]:
bits('\xe2\x88\x80')

"00000000000000000010001000000000"

In [38]:
function f(x,y)
  x + y
end
 ∑ = f

f (generic function with 1 method)

In [39]:
f(2, 3) ==  ∑(2, 3)

true

In [40]:
function hypot(x,y)
  x = abs(x)
  y = abs(y)
  if x > y
    r = y/x
    return x*sqrt(1+r*r)
  end
  if y == 0
    return zero(x)
  end
  r = x/y
  return y*sqrt(1+r*r)
end

hypot (generic function with 1 method)

In [41]:
hypot(3, 4)

5.0

In [42]:
+(1,2,3)

6

In [43]:
fadd = +
fadd(1, 2, 3)

6

In [45]:
[1 2 3]

1x3 Array{Int64,2}:
 1  2  3

In [46]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [47]:
[1 2; 3 4; 5 6]

3x2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [48]:
hcat(1, 2, 3) == [1 2 3]

true

In [49]:
vcat(1, 2, 3) == [1, 2, 3]

true

In [58]:
hvcat( (2, 2, 2) , 1, 2, 3, 4, 5, 6) == [1 2; 3 4; 5 6]

true

In [66]:
hvcat(2, 1, 2, 3, 4, 5, 6) == [1 2; 3 4; 5 6]

true

In [71]:
mx = [1 2im; 3im 4; 5 6im]

3x2 Array{Complex{Int64},2}:
 1+0im  0+2im
 0+3im  4+0im
 5+0im  0+6im

In [72]:
mx'

2x3 Array{Complex{Int64},2}:
 1+0im  0-3im  5+0im
 0-2im  4+0im  0-6im

In [73]:
mx.'

2x3 Array{Complex{Int64},2}:
 1+0im  0+3im  5+0im
 0+2im  4+0im  0+6im

In [75]:
1:100 == colon(1, 100)

true

In [76]:
# See Functions: Operators With Special Names

In [77]:
x -> x^2 + 2x - 1

(anonymous function)

In [78]:
function (x)
   x^2 + 2x - 1
end

(anonymous function)

In [79]:
map(x -> x^2 + 2x - 1, [1,3,-1])

3-element Array{Int64,1}:
  2
 14
 -2

In [80]:
function foo(a,b)
    a+b, a*b
end
foo(2, 3)

(5,6)

In [81]:
bar(a,b,x...) = (a,b,x)
bar(1,2,3,4,5,6)

(1,2,(3,4,5,6))

In [82]:
baz(a,b) = a + b
args = [1,2]
baz(args...)

3

In [86]:
function bonus_add(a, b, c=5)
    a + b + c
end
bonus_add(2, 3) == bonus_add(2, 3, 5)

true

In [91]:
function extra_add(a; b=3, c=5)
    a + b + c
end
extra_add(2, b=4, c=4) == extra_add(0, b=5) == extra_add(2)

true

In [95]:
map(x->begin
           if x < 0 && iseven(x)
               return 0
           elseif x == 0
               return 1
           else
               return x
           end
       end,
[1, 2, 3]) == map([1, 2, 3]) do x # Am I writing ruby? ^_^
    if x < 0 && iseven(x)
        return 0
    elseif x == 0
        return 1
    else
        return x
    end
end # The do x syntax creates an anonymous function with argument x and passes it as the first argument

true

In [101]:
begin
    x = 1
    y = 2
    x + y
end == (x = 1; y = 2; x + y)

true

In [102]:
# Although it is typical, there is no requirement that begin blocks be multiline or that (;) chains be single-line
begin x = 1; y = 2; x + y end == (x = 1;
        y = 2;
        x + y)

true

In [105]:
function test_order(x, y)
 if x < y
   println("$x is less than $y")
 elseif x > y
   println("$x is greater than $y")
 else
   println("$x is equal to $y")
 end
end

test_order (generic function with 1 method)

In [106]:
test_order(1, 3)

1 is less than 3


`if` blocks are “leaky”, i.e. they do not introduce a local scope. This means that new variables defined inside the `ìf` clauses can be used after the `if` block, even if they weren’t defined before. 

In [107]:
function test_order_leaky(x,y)
 if x < y
   relation = "less than"
 elseif x == y
   relation = "equal to"
 end
 println("$x is ", relation, " $y.")
end

test_order_leaky (generic function with 1 method)

In [110]:
test_order_leaky(1, 3)

1 is less than 3.


In [111]:
test_order_leaky(11, 3)

LoadError: LoadError: UndefVarError: relation not defined
while loading In[111], in expression starting on line 1

In [112]:
5 > 1 && println("5 > 1")

5 > 1


In [113]:
4 < 1 || println("false")

false


In [114]:
i = 1
while i <= 5
 println(i)
 i += 1
end

1
2
3
4
5


In [116]:
for j=1:5; println(j); end

1
2
3
4
5


In [117]:
for s in ["foo","bar","baz"]
 println(s)
end

foo
bar
baz


In [119]:
# OH! This is AWESOME!
for i = 1:2, j in ["apple", "banana", "pear"]
 println((i, j))
end

(1,"apple")
(1,"banana")
(1,"pear")
(2,"apple")
(2,"banana")
(2,"pear")


In [120]:
positive_exp(x) = x>=0 ? exp(-x) : throw(DomainError())

positive_exp (generic function with 1 method)

In [121]:
positive_exp(1)

0.36787944117144233

In [122]:
positive_exp(-100)

LoadError: LoadError: DomainError:
while loading In[122], in expression starting on line 1

In [123]:
typeof(DomainError()) <: Exception

true

In [125]:
throw(UndefVarError(:a_missing_variable))

LoadError: LoadError: UndefVarError: a_missing_variable not defined
while loading In[125], in expression starting on line 1

In [126]:
fussy_sqrt(x) = x >= 0 ? sqrt(x) : error("negative x not allowed")

fussy_sqrt (generic function with 1 method)

In [127]:
fussy_sqrt(100)

10.0

In [128]:
fussy_sqrt(-250)

LoadError: LoadError: negative x not allowed
while loading In[128], in expression starting on line 1

In [129]:
function verbose_fussy_sqrt(x)
 println("before fussy_sqrt")
 r = fussy_sqrt(x)
 println("after fussy_sqrt")
 return r
end

verbose_fussy_sqrt (generic function with 1 method)

In [130]:
verbose_fussy_sqrt(-1)

before fussy_sqrt


LoadError: LoadError: negative x not allowed
while loading In[130], in expression starting on line 1

In [131]:
info("Hi"); 1+1
warn("Hi"); 1+1
error("Hi"); 1+1

INFO: Hi


LoadError: LoadError: Hi
while loading In[131], in expression starting on line 3

In [132]:
 try error() end #Returns nothing

In [133]:
try
    println("step 1 ok")
    error("step 2 failed")
    println("step 3 was never reached")
catch e
    if isa(e, DomainError)
        # Obviously, it's not
    else
        println(e)
    end
finally
    println("step 4 is ensured")
end
    

step 1 ok
ErrorException("step 2 failed")
step 4 is ensured


In [134]:
# https://github.com/transcranial/jupyter-themer
run(`pip install jupyter-themer`)

  Running setup.py bdist_wheel for jupyter-themer: started
  Running setup.py bdist_wheel for jupyter-themer: finished with status 'done'
  Stored in directory: /Users/utensil/Library/Caches/pip/wheels/de/60/66/02ff107061ba3f1122bc30954652709197d6cd66c0ccdcdfb0
Successfully built jupyter-themer


In [148]:
run(`jupyter-themer -c tomorrow-night-eighties`)

Custom jupyter notebook theme created - refresh any open jupyter notebooks to apply theme.


In [149]:
run(`jupyter-themer`)

Jupyter notebook reverted to default style.


In [150]:
function producer()
    produce("start")
    for n=1:4
        produce(2n)
    end
    produce("stop")
end

producer (generic function with 1 method)

In [155]:
p = Task(producer)

Task (runnable) @0x000000010d322620

In [156]:
for i=0:6
    got = consume(p)
    println("$(typeof(got)): $got")
end

ASCIIString: start
Int64: 2
Int64: 4
Int64: 6
Int64: 8
ASCIIString: stop
Tuple{}: ()


In [157]:
for got in Task(producer)
    println("$(typeof(got)): $got")
end

ASCIIString: start
Int64: 2
Int64: 4
Int64: 6
Int64: 8
ASCIIString: stop


In [158]:
p.state

:done

<div class="wy-table-responsive"><table border="1" class="docutils" id="man-scope-table">
<colgroup>
<col width="28%">
<col width="27%">
<col width="45%">
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">Scope name</th>
<th class="head" colspan="2">block/construct introducing this kind of scope</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><a class="reference internal" href="#man-global"><span>global</span></a></td>
<td colspan="2"><div class="first last line-block">
<div class="line">module, baremodule, at interactive prompt (REPL)</div>
</div>
</td>
</tr>
<tr class="row-odd"><td rowspan="2"><a class="reference internal" href="#man-local-scope"><span>local</span></a></td>
<td><a class="reference internal" href="#man-soft-scope"><span>soft</span></a></td>
<td><div class="first last line-block">
<div class="line">for, while, list-comprehensions,
try-catch-finally, let</div>
</div>
</td>
</tr>
<tr class="row-even"><td><a class="reference internal" href="#man-hard-scope"><span>hard</span></a></td>
<td><div class="first last line-block">
<div class="line">functions (either syntax, anonymous &amp; do-blocks)</div>
<div class="line">type, immutable, macro</div>
</div>
</td>
</tr>
</tbody>
</table></div>

In [162]:
let
    global x = "global"
    # a new scope
    let
        local x = "local_let"
        # not a new scope
        begin
            # not a new scope
            if x == "local_let"
                println(x)
            end
        end
        let
            local x = "local_let_2"
            println(x)
        end
    end
end
x

local_let
local_let_2


"global"

`for` loops and comprehensions have the following behavior: any new variables introduced in their body scopes are freshly allocated for each loop iteration. This is in contrast to `while` loops which reuse the variables for all iterations. Therefore these constructs are similar to `while` loops with `let` blocks inside

In [163]:
i = 0
for i = 1:3
end
i  # here equal to 3

3

In [164]:
x = 0
[ x for x=1:3 ]
x  # here still equal to 0

0

In [3]:
i = 0
j = 3
while j > i
    println((i, j))
    j -= 1
end
(i, j)

(0,3)
(0,2)
(0,1)


(0,0)

In [4]:
e

e = 2.7182818284590...

In [5]:
const K = e * π

8.539734222673566

In [6]:
(1+2)::Int

3

In [12]:
function foo()
 x::Int8 = 100
 x
end

foo (generic function with 1 method)

In [13]:
typeof(foo())

Int8

In [20]:
local y::Int8 = 10

10

In [21]:
y = 200

200

In [22]:
y

200

In [23]:
typeof(y)

Int64

In [24]:
local y::Int8=200

LoadError: LoadError: InexactError()
while loading In[24], in expression starting on line 1

```julia
abstract Number
abstract Real     <: Number
abstract AbstractFloat <: Real
abstract Integer  <: Real
abstract Signed   <: Integer
abstract Unsigned <: Integer
```

In [25]:
Integer <: Number

true

In [26]:
Integer <: AbstractFloat

false

In [27]:
bitstype 7 sevenbit

LoadError: LoadError: invalid number of bits in type sevenbit
while loading In[27], in expression starting on line 1

In [28]:
bitstype 128 onetwoeightbits

In [29]:
bitstype 128 ∰

In [30]:
sizeof(∰)

16

In [32]:
type footype
     bar
     baz::Int
     qux::Float64
end

In [36]:
ft = footype("bar", 8, 12.9)

footype("bar",8,12.9)

In [37]:
footype("bar", 8, 12)

footype("bar",8,12.0)

In [38]:
footype("bar", 8, "12.9")

LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Float64}, ::ASCIIString)
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{Float64}, !Matched::Int8)
  convert(::Type{Float64}, !Matched::Int16)
  ...
while loading In[38], in expression starting on line 1

In [39]:
typeof(ft)

footype

In [40]:
fieldnames(ft)

3-element Array{Symbol,1}:
 :bar
 :baz
 :qux

In [41]:
fieldnames(footype)

3-element Array{Symbol,1}:
 :bar
 :baz
 :qux

In [42]:
ft.bar = 1//2

1//2

Composite types with no fields are singletons; there can be only one instance of such types:

In [43]:
type NoFields
end

In [44]:
is(NoFields(), NoFields())

true

In [45]:
immutable MyComplex
  real::Float64
  imag::Float64
end

In [46]:
c = MyComplex(12, 34)

MyComplex(12.0,34.0)

In [47]:
c.real

12.0

In [48]:
c.real = 13

LoadError: LoadError: type MyComplex is immutable
while loading In[48], in expression starting on line 1

In [49]:
IntOrString = Union{Int,AbstractString}

Union{AbstractString,Int64}

In [50]:
1 :: IntOrString

1

In [51]:
"1" :: IntOrString

"1"

In [52]:
1.0 :: IntOrString

LoadError: LoadError: TypeError: typeassert: expected Union{AbstractString,Int64}, got Float64
while loading In[52], in expression starting on line 1

In [53]:
type MyPoint{T}
  x::T
  y::T
end

In [54]:
mp = MyPoint(1, 2)

MyPoint{Int64}(1,2)

In [55]:
mp = MyPoint(1, "2")

LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{MyPoint{T}}, ::Int64, ::ASCIIString)
This may have arisen from a call to the constructor MyPoint{T}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  MyPoint{T}(::T, !Matched::T)
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, !Matched::T)
while loading In[55], in expression starting on line 1

In [57]:
MyPoint{Float64} <: MyPoint

true

In [58]:
Float64 <: Real

true

In [59]:
MyPoint{Float64} <: MyPoint{Real}

false

In [60]:
abstract Pointly{T}

In [61]:
Pointly{Int} <: Pointly

true

In [63]:
type SpecificPoint{T} <: Pointly{T}
  x::T
  y::T
end

In [65]:
SpecificPoint{AbstractString} <: Pointly

true

In [66]:
SpecificPoint("a", "b")

SpecificPoint{ASCIIString}("a","b")

In [67]:
abstract RealPoint{T<:Real}

In [72]:
RealPoint{Float32} <: RealPoint

true

In [73]:
Tuple{Int,AbstractString} <: Tuple{Real,Any}

true

In [74]:
Tuple{Int,AbstractString} <: Tuple{Real,}

false

In [77]:
(1.0, 1.0) :: Tuple{Vararg{Real}}

(1.0,1.0)

In [78]:
isa(("1",1,2), Tuple{AbstractString,Vararg{Int}})

true

In [79]:
isa(("1",1,2,3.0), Tuple{AbstractString,Vararg{Int}})

false

In [81]:
isa(Float64, Type{Float64})

true

In [82]:
isa(Float64, Type{Real})

false

In [83]:
bitstype 64 MyPtr{T}

In [84]:
MyPtr{Float64} <: MyPtr{Real}

false

In [85]:
MyPtr{Float64} <: MyPtr

true

In [86]:
MyPtr{onetwoeightbits}

MyPtr{onetwoeightbits}

In [88]:
typealias MyAliasPtr MyPtr

MyPtr{T}

In [89]:
MyAliasPtr <: MyPtr

true

In [90]:
MyPtr <: MyPtr

true

In [91]:
Array{Float64,1} <: Array{Float64} <: Array

true

In [92]:
typealias MyVector{T} Array{T,1}
typealias MyMatrix{T} Array{T,2}

Array{T,2}

In [93]:
super(Float64)

AbstractFloat

In [94]:
super(ans)

Real

In [95]:
super(ans)

Number

In [96]:
super(ans)

Any

In [97]:
function firstlast(b::Bool)
    return b ? "First" : "Last"
end

println(firstlast(true))

First


In [98]:
firstlast(::Type{Val{true}}) = "First"
firstlast(::Type{Val{false}}) = "Last"

firstlast (generic function with 3 methods)

In [99]:
@doc firstlast

No documentation found.

`firstlast` is a generic `Function`.

```julia
# 3 methods for generic function "firstlast":
firstlast(b::Bool) at In[97]:2
firstlast(::Type{Val{true}}) at In[98]:1
firstlast(::Type{Val{false}}) at In[98]:2
```


In [106]:
firstlast(Val{true})

"First"

In [107]:
firstlast(::Type{Val{3}}) = "3"

firstlast (generic function with 4 methods)

In [108]:
firstlast(Val{3})

"3"

In [109]:
firstlast(3)

LoadError: LoadError: MethodError: `firstlast` has no method matching firstlast(::Int64)
while loading In[109], in expression starting on line 1

In [110]:
isnull(3)

LoadError: LoadError: MethodError: `isnull` has no method matching isnull(::Int64)
while loading In[110], in expression starting on line 1

In [111]:
isnull(Nullable(3))

false

In [112]:
get(Nullable{Float64}())

LoadError: LoadError: NullException()
while loading In[112], in expression starting on line 1

In [113]:
methods(display)

# 20 methods for generic function "display":
display() at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:53
display(d::Display, mime::AbstractString, x) at multimedia.jl:110
display(mime::AbstractString, x) at multimedia.jl:111
display(d::TextDisplay, M::MIME{symbol("text/plain")}, x) at multimedia.jl:119
display(d::TextDisplay, x) at multimedia.jl:120
display(m::MIME{mime}, x) at multimedia.jl:170
display(d::Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, ::MIME{symbol("text/plain")}, x) at REPL.jl:112
display(d::Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, md::Base.Markdown.MD) at markdown/render/terminal/render.jl:126
display(d::Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, md::Array{Base.Markdown.MD,1}) at markdown/Markdown.jl:61
display(d::Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, x) at REPL.jl:117
display(d::IPythonDisplay.InlineDisplay, ::MIME{symbol("text/html")}, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:19
display(d::IPythonDisplay.InlineDisplay, ::MIME{symbol("text/latex")}, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:19
display(d::IPythonDisplay.InlineDisplay, ::MIME{symbol("image/svg+xml")}, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:19
display(d::IPythonDisplay.InlineDisplay, ::MIME{symbol("image/png")}, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:19
display(d::IPythonDisplay.InlineDisplay, ::MIME{symbol("image/jpeg")}, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:19
display(d::IPythonDisplay.InlineDisplay, ::MIME{symbol("text/plain")}, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:19
display(d::IPythonDisplay.InlineDisplay, ::MIME{symbol("text/markdown")}, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:19
display(d::IPythonDisplay.InlineDisplay, m::MIME{symbol("application/x-latex")}, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:29
display(d::IPythonDisplay.InlineDisplay, x) at /Users/utensil/.julia/v0.4/IJulia/src/inline.jl:34
display(x) at multimedia.jl:162

In [115]:
optional_function(a=1, b=2) = a + b

optional_function (generic function with 3 methods)

In [116]:
methods(optional_function)

# 3 methods for generic function "optional_function":
optional_function() at In[115]:1
optional_function(a) at In[115]:1
optional_function(a, b) at In[115]:1

In [119]:
println("abc\ufff9abc\ufffbabc")

abcabcabc


In [122]:
println("abc\ufffaabc\ufffbabc")

abcabcabc


In [123]:
println("\u202eABCDE\u202dXYZ")

‮ABCDE‭XYZ


In [124]:
println("大字\u200d小字")

大字‍小字


In [125]:
Base.call(x::Number, arg) = x * arg

call (generic function with 1094 methods)

In [126]:
a_number=10

10

In [127]:
10(20)

200

In [128]:
function emptyfunc
end

emptyfunc (generic function with 0 methods)

In [1]:
type OrderedPair
  x::Real
  y::Real

  OrderedPair(x,y) = x > y ? error("out of order") : new(x,y)
end

In [2]:
OrderedPair(1, 2)

OrderedPair(1,2)

In [3]:
OrderedPair(2, 1)

LoadError: LoadError: out of order
while loading In[3], in expression starting on line 1

In [4]:
type Foo
  bar
  baz

  Foo(bar,baz) = new(bar,baz)
end

In [1]:
type SelfReferential
  obj::SelfReferential
end

In [2]:
type BetterSelfReferential
  obj::BetterSelfReferential

  BetterSelfReferential() = (x = new(); x.obj = x)
end

In [4]:
sr = SelfReferential()

LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{SelfReferential})
This may have arisen from a call to the constructor SelfReferential(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{T}, !Matched::T)
  SelfReferential(, !Matched::SelfReferential)
  SelfReferential(, !Matched::Any)
  ...
while loading In[4], in expression starting on line 1

In [5]:
bsr = BetterSelfReferential()

BetterSelfReferential(BetterSelfReferential(#= circular reference =#))

In [6]:
is(bsr, bsr.obj.obj)

true

In some cases you could consider adding methods to Base.convert instead of defining a constructor, because defining a convert() method automatically defines a corresponding constructor, while the reverse is not true. That is, defining Base.convert(::Type{T}, args...) = ... automatically defines a constructor T(args...) = ....



In [7]:
type SummedArray{T<:Number,S<:Number}
    data::Vector{T}
    sum::S

    function call{T}(::Type{SummedArray}, a::Vector{T})
        S = widen(T)
        new{T,S}(a, sum(S, a))
    end
end

In [11]:
sa = SummedArray(Vector{Int32}([1, 2, 3]))

SummedArray{Int32,Int64}(Int32[1,2,3],6)

In [12]:
sa.sum

6

```
promote_rule(::Type{UInt8}, ::Type{Int8}) = Int
promote_rule(::Type{BigInt}, ::Type{Int8}) = BigInt
```

In [13]:
promote_type(Int8, UInt16)

Int64

```julia
promote_rule{T<:Integer}(::Type{Rational{T}}, ::Type{T}) = Rational{T}
promote_rule{T<:Integer,S<:Integer}(::Type{Rational{T}}, ::Type{S}) = Rational{promote_type(T,S)}
promote_rule{T<:Integer,S<:Integer}(::Type{Rational{T}}, ::Type{Rational{S}}) = Rational{promote_type(T,S)}
promote_rule{T<:Integer,S<:AbstractFloat}(::Type{Rational{T}}, ::Type{S}) = promote_type(T,S)
```

In [14]:
immutable Squares
   count::Int
end
Base.start(::Squares) = 1
Base.next(S::Squares, state) = (state*state, state+1)
Base.done(S::Squares, s) = s > S.count;
Base.eltype(::Type{Squares}) = Int # Note that this is defined for the type
Base.length(S::Squares) = S.count;

In [15]:
for i in Squares(7)
   println(i)
end

1
4
9
16
25
36
49


In [16]:
length(Squares(100)) == 100

true

In [17]:
25 in Squares(10)

true

In [18]:
mean(Squares(100)), std(Squares(100))

(3383.5,3024.355854282583)

In [19]:
 collect(Squares(100))'

1x100 Array{Int64,2}:
 1  4  9  16  25  36  49  64  81  100  …  9025  9216  9409  9604  9801  10000

In [21]:
Base.sum(S::Squares) = (n = S.count; return n*(n+1)*(2n+1)÷6)
       sum(Squares(1803))

1955361914

In [23]:
1 + 2 | 3 == (1 + 2) | 3

true

In [24]:
1 .* 2

2

```julia
module MyModule
using Lib

using BigLib: thing1, thing2

import Base.show

importall OtherLib

export MyType, foo

type MyType
    x
end

bar(x) = 2x
foo(a::MyType) = bar(a.x) + 1

show(io, a::MyType) = print(io, "MyType $(a.x)")
end
```

```julia
module Parent

module Utils
...
end

using .Utils

...
end
```

In [25]:
?@time

```
@time
```

A macro to execute an expression, printing the time it took to execute, the number of allocations, and the total number of bytes its execution caused to be allocated, before returning the value of the expression.


In [35]:
@time collect(Squares(300000000))'

  4.591638 seconds (10 allocations: 4.470 GB, 4.91% gc time)


1x300000000 Array{Int64,2}:
 1  4  9  16  25  36  49  64  81  100  121  144  169  …  90000000000000000

to re-use documentation between different versions of a function:

```
@doc "..." foo!
@doc (@doc foo!) foo
    ```

In [36]:
foo = (x) -> 0

(anonymous function)

In [37]:
@doc "fooing" foo

In [38]:
@doc foo

fooing


In [39]:
"`abc` is just _ABC_ as we know"
abc = "abc"

`abc` is just _ABC_ as we know


In [40]:
@doc abc

`abc` is just _ABC_ as we know


In [1]:
intarray = Array(Int64, 100)

100-element Array{Int64,1}:
 2190216240
 2153360720
 2153360736
 2153360752
 2153360768
 2225828400
 2225828432
 2225828528
 2205896976
 2225828592
 2222477008
 2206633168
 2206633232
          ⋮
          0
          0
          0
          0
          0
          0
          0
          0
          0
          0
          0
          0

In [2]:
intarray = zeros(Int64, 100)

100-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [3]:
eltype(intarray)

Int64

In [4]:
length(intarray)

100

In [5]:
ndims(intarray)

1

In [6]:
size(intarray)

(100,)

In [7]:
strides(intarray)

(1,)

In [8]:
@doc strides

```
strides(A)
```

Returns a tuple of the memory strides in each dimension


In [10]:
array = cell((3, 3))

3x3 Array{Any,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef
 #undef  #undef  #undef

In [11]:
m = zeros((3, 3))

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [12]:
size(m)

(3,3)

In [13]:
size(m, 2)

3

In [14]:
strides(m)

(1,3)

In [15]:
rand(3)

3-element Array{Float64,1}:
 0.262588
 0.68179 
 0.995355

In [17]:
randn(3)

3-element Array{Float64,1}:
  1.62027
 -1.53208
  2.52513

In [18]:
@doc eye

```
eye(m, n)
```

`m`-by-`n` identity matrix

```
eye(A)
```

Constructs an identity matrix of the same dimensions and type as `A`.

```
eye(n)
```

`n`-by-`n` identity matrix


In [19]:
ey = eye(3, 2)

3x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0
 0.0  0.0

In [20]:
fm = fill(3, (3, 3))

3x3 Array{Int64,2}:
 3  3  3
 3  3  3
 3  3  3

<table border="1" class="docutils">
<colgroup>
<col width="59%">
<col width="41%">
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">Expression</th>
<th class="head">Calls</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><code class="docutils literal"><span class="pre">[A;</span> <span class="pre">B;</span> <span class="pre">C;</span> <span class="pre">...]</span></code></td>
<td><a class="reference internal" href="../../stdlib/arrays/#Base.vcat" title="Base.vcat"><code class="xref jl jl-func docutils literal"><span class="pre">vcat()</span></code></a></td>
</tr>
<tr class="row-odd"><td><code class="docutils literal"><span class="pre">[A</span> <span class="pre">B</span> <span class="pre">C</span> <span class="pre">...]</span></code></td>
<td><a class="reference internal" href="../../stdlib/arrays/#Base.hcat" title="Base.hcat"><code class="xref jl jl-func docutils literal"><span class="pre">hcat()</span></code></a></td>
</tr>
<tr class="row-even"><td><code class="docutils literal"><span class="pre">[A</span> <span class="pre">B;</span> <span class="pre">C</span> <span class="pre">D;</span> <span class="pre">...]</span></code></td>
<td><a class="reference internal" href="../../stdlib/arrays/#Base.hvcat" title="Base.hvcat"><code class="xref jl jl-func docutils literal"><span class="pre">hvcat()</span></code></a></td>
</tr>
</tbody>
</table>

In [21]:
a, b, c, d, e, f = 1, 2, 3, 4, 5, 6
 [a b c; d e f]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [22]:
hvcat((3,3), a,b,c,d,e,f)

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [23]:
[a b;c d; e f]

3x2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [24]:
hvcat((2,2,2), a,b,c,d,e,f)

3x2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [25]:
@doc hvcat

```
hvcat(rows::Tuple{Vararg{Int}}, values...)
```

Horizontal and vertical concatenation in one call. This function is called for block matrix syntax. The first argument specifies the number of arguments to concatenate in each block row.

```jldoctest
julia> a, b, c, d, e, f = 1, 2, 3, 4, 5, 6
(1,2,3,4,5,6)

julia> [a b c; d e f]
2x3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> hvcat((3,3), a,b,c,d,e,f)
2x3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> [a b;c d; e f]
3x2 Array{Int64,2}:
 1  2
 3  4
 5  6

julia> hvcat((2,2,2), a,b,c,d,e,f)
3x2 Array{Int64,2}:
 1  2
 3  4
 5  6
```

If the first argument is a single integer `n`, then all block rows are assumed to have `n` block columns.


<div class="section" id="indexing">
<span id="man-array-indexing"></span><h3>Indexing<a class="headerlink" href="#indexing" title="Permalink to this headline">¶</a></h3>
<p>The general syntax for indexing into an n-dimensional array A is:</p>
<div class="highlight-julia"><div class="highlight"><pre><span></span><span class="n">X</span> <span class="o">=</span> <span class="n">A</span><span class="p">[</span><span class="n">I_1</span><span class="p">,</span> <span class="n">I_2</span><span class="p">,</span> <span class="o">...</span><span class="p">,</span> <span class="n">I_n</span><span class="p">]</span>
</pre></div>
</div>
<p>where each <code class="docutils literal"><span class="pre">I_k</span></code> may be:</p>
<ol class="arabic simple">
<li>A scalar integer</li>
<li>A <code class="docutils literal"><span class="pre">Range</span></code> of the form <code class="docutils literal"><span class="pre">a:b</span></code>, or <code class="docutils literal"><span class="pre">a:b:c</span></code></li>
<li>A <code class="docutils literal"><span class="pre">:</span></code> or <code class="docutils literal"><span class="pre">Colon()</span></code> to select entire dimensions</li>
<li>An arbitrary integer vector, including the empty vector <code class="docutils literal"><span class="pre">[]</span></code></li>
<li>A boolean vector</li>
</ol>
<p>The result <code class="docutils literal"><span class="pre">X</span></code> generally has dimensions
<code class="docutils literal"><span class="pre">(length(I_1),</span> <span class="pre">length(I_2),</span> <span class="pre">...,</span> <span class="pre">length(I_n))</span></code>, with location
<code class="docutils literal"><span class="pre">(i_1,</span> <span class="pre">i_2,</span> <span class="pre">...,</span> <span class="pre">i_n)</span></code> of <code class="docutils literal"><span class="pre">X</span></code> containing the value
<code class="docutils literal"><span class="pre">A[I_1[i_1],</span> <span class="pre">I_2[i_2],</span> <span class="pre">...,</span> <span class="pre">I_n[i_n]]</span></code>. Trailing dimensions
indexed with scalars are dropped. For example, the dimensions of <code class="docutils literal"><span class="pre">A[I,</span> <span class="pre">1]</span></code> will be
<code class="docutils literal"><span class="pre">(length(I),)</span></code>. Boolean vectors are first transformed with <code class="docutils literal"><span class="pre">find</span></code>; the size of
a dimension indexed by a boolean vector will be the number of true values in the vector.
As a special part of this syntax, the <code class="docutils literal"><span class="pre">end</span></code> keyword may be used to represent the last
index of each dimension within the indexing brackets, as determined by the size of the
innermost array being indexed.</p>
<p>Alternatively, single elements of a multidimensional array can be indexed as</p>
<div class="highlight-julia"><div class="highlight"><pre><span></span><span class="n">x</span> <span class="o">=</span> <span class="n">A</span><span class="p">[</span><span class="n">I</span><span class="p">]</span>
</pre></div>
</div>
<p>where <code class="docutils literal"><span class="pre">I</span></code> is a <code class="docutils literal"><span class="pre">CartesianIndex</span></code>, effectively an <code class="docutils literal"><span class="pre">n</span></code>-tuple of integers.
See <a class="reference internal" href="#man-array-iteration"><span>Iteration</span></a> below.</p>
<p>Indexing syntax is equivalent to a call to <code class="docutils literal"><span class="pre">getindex</span></code>:</p>
<div class="highlight-julia"><div class="highlight"><pre><span></span><span class="n">X</span> <span class="o">=</span> <span class="n">getindex</span><span class="p">(</span><span class="n">A</span><span class="p">,</span> <span class="n">I_1</span><span class="p">,</span> <span class="n">I_2</span><span class="p">,</span> <span class="o">...</span><span class="p">,</span> <span class="n">I_n</span><span class="p">)</span>
</pre></div>
</div>
<p>Example:</p>
<div class="highlight-julia"><div class="highlight"><pre><span></span><span class="n">julia</span><span class="o">&gt;</span> <span class="n">x</span> <span class="o">=</span> <span class="n">reshape</span><span class="p">(</span><span class="mi">1</span><span class="p">:</span><span class="mi">16</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">4</span><span class="p">)</span>
<span class="mi">4</span><span class="n">x4</span> <span class="n">Array</span><span class="p">{</span><span class="kt">Int64</span><span class="p">,</span><span class="mi">2</span><span class="p">}:</span>
 <span class="mi">1</span>  <span class="mi">5</span>   <span class="mi">9</span>  <span class="mi">13</span>
 <span class="mi">2</span>  <span class="mi">6</span>  <span class="mi">10</span>  <span class="mi">14</span>
 <span class="mi">3</span>  <span class="mi">7</span>  <span class="mi">11</span>  <span class="mi">15</span>
 <span class="mi">4</span>  <span class="mi">8</span>  <span class="mi">12</span>  <span class="mi">16</span>

<span class="n">julia</span><span class="o">&gt;</span> <span class="n">x</span><span class="p">[</span><span class="mi">2</span><span class="p">:</span><span class="mi">3</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span><span class="k">end</span><span class="o">-</span><span class="mi">1</span><span class="p">]</span>
<span class="mi">2</span><span class="n">x2</span> <span class="n">Array</span><span class="p">{</span><span class="kt">Int64</span><span class="p">,</span><span class="mi">2</span><span class="p">}:</span>
 <span class="mi">6</span>  <span class="mi">10</span>
 <span class="mi">7</span>  <span class="mi">11</span>
</pre></div>
</div>
<p>Empty ranges of the form <code class="docutils literal"><span class="pre">n:n-1</span></code> are sometimes used to indicate the inter-index
location between <code class="docutils literal"><span class="pre">n-1</span></code> and <code class="docutils literal"><span class="pre">n</span></code>.  For example, the <a class="reference internal" href="../../stdlib/sort/#Base.searchsorted" title="Base.searchsorted"><code class="xref jl jl-func docutils literal"><span class="pre">searchsorted()</span></code></a> function uses
this convention to indicate the insertion point of a value not found in a sorted
array:</p>
<div class="highlight-julia"><div class="highlight"><pre><span></span><span class="n">julia</span><span class="o">&gt;</span> <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span><span class="mi">2</span><span class="p">,</span><span class="mi">5</span><span class="p">,</span><span class="mi">6</span><span class="p">,</span><span class="mi">7</span><span class="p">];</span>

<span class="n">julia</span><span class="o">&gt;</span> <span class="n">searchsorted</span><span class="p">(</span><span class="n">a</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
<span class="mi">3</span><span class="p">:</span><span class="mi">2</span>
</pre></div>
</div>
</div>

In [26]:
 x = reshape(1:16, 4, 4)

4x4 Array{Int64,2}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [27]:
 x[2:3, 2:end-1]

2x2 Array{Int64,2}:
 6  10
 7  11

In [28]:
3:2

3:2

In [29]:
typeof(3:2)

UnitRange{Int64}

In [30]:
typeof(1:50)

UnitRange{Int64}

In [31]:
A = rand(4,3)
B = sub(A, 1:3, 2:3)
(A, B)

(
4x3 Array{Float64,2}:
 0.897381  0.230063   0.999231 
 0.387111  0.0517558  0.188619 
 0.80081   0.984446   0.0437768
 0.169907  0.683732   0.517761 ,

3x2 SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},1}:
 0.230063   0.999231 
 0.0517558  0.188619 
 0.984446   0.0437768)

In [32]:
square(x) = x^2
 @vectorize_1arg Number square

square (generic function with 4 methods)

In [33]:
methods(square)

# 4 methods for generic function "square":
square{T<:Number}(::AbstractArray{T<:Number,1}) at operators.jl:380
square{T<:Number}(::AbstractArray{T<:Number,2}) at operators.jl:381
square{T<:Number}(::AbstractArray{T<:Number,N}) at operators.jl:383
square(x) at In[32]:1

In [34]:
square(A)

4x3 Array{Float64,2}:
 0.805292   0.052929    0.998462 
 0.149855   0.00267866  0.035577 
 0.641296   0.969134    0.0019164
 0.0288685  0.467489    0.268077 

In [35]:
a = rand(2,1); A = rand(2,3);
(a, A)

(
2x1 Array{Float64,2}:
 0.243233
 0.467999,

2x3 Array{Float64,2}:
 0.911001  0.851159  0.112441
 0.190415  0.946762  0.682602)

In [36]:
broadcast(+, a, A)

2x3 Array{Float64,2}:
 1.15423   1.09439  0.355674
 0.658414  1.41476  1.1506  

In [37]:
b = rand(1,2)
broadcast(+, a, b)

2x2 Array{Float64,2}:
 1.02773  1.03444
 1.2525   1.2592 

In [38]:
spzeros(3,5)

3x5 sparse matrix with 0 Float64 entries:

In [39]:
speye(3,5)

3x5 sparse matrix with 3 Float64 entries:
	[1, 1]  =  1.0
	[2, 2]  =  1.0
	[3, 3]  =  1.0

In [40]:
I = [1, 4, 3, 5]; J = [4, 7, 18, 9]; V = [1, 2, -5, 3];
S = sparse(I,J,V)

5x18 sparse matrix with 4 Int64 entries:
	[1 ,  4]  =  1
	[4 ,  7]  =  2
	[5 ,  9]  =  3
	[3 , 18]  =  -5

In [41]:
findn(S)

([1,4,5,3],[4,7,9,18])

In [42]:
findnz(S)

([1,4,5,3],[4,7,9,18],[1,2,3,-5])

In [44]:
@doc findn

```
findn(A)
```

Return a vector of indexes for each dimension giving the locations of the non-zeros in `A` (determined by `A[i]!=0`).


In [45]:
@doc findnz

```
findnz(A)
```

Return a tuple `(I, J, V)` where `I` and `J` are the row and column indexes of the non-zero values in matrix `A`, and `V` is a vector of the non-zero values.


In [46]:
sparse(eye(5))

5x5 sparse matrix with 5 Float64 entries:
	[1, 1]  =  1.0
	[2, 2]  =  1.0
	[3, 3]  =  1.0
	[4, 4]  =  1.0
	[5, 5]  =  1.0

In [47]:
issparse(speye(5))

true

In [48]:
full(S)

5x18 Array{Int64,2}:
 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0   0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0   0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  -5
 0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0   0
 0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0   0

<div class="section" id="linear-algebra">
<h1>Linear algebra<a class="headerlink" href="#linear-algebra" title="Permalink to this headline">¶</a></h1>
<div class="section" id="matrix-factorizations">
<h2>Matrix factorizations<a class="headerlink" href="#matrix-factorizations" title="Permalink to this headline">¶</a></h2>
<p><a class="reference external" href="https://en.wikipedia.org/wiki/Matrix_decomposition">Matrix factorizations (a.k.a. matrix decompositions)</a>
compute the factorization of a matrix into a product of matrices, and
are one of the central concepts in linear algebra.</p>
<p>The following table summarizes the types of matrix factorizations that have been
implemented in Julia. Details of their associated methods can be found
in the <a class="reference internal" href="../../stdlib/linalg/#stdlib-linalg"><span>Linear Algebra</span></a> section of the standard library documentation.</p>
<div class="wy-table-responsive"><table border="1" class="docutils">
<colgroup>
<col width="18%">
<col width="82%">
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">Cholesky</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Cholesky_decomposition">Cholesky factorization</a></td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">CholeskyPivoted</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Pivot_element">Pivoted</a> Cholesky factorization</td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">LU</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/LU_decomposition">LU factorization</a></td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">LUTridiagonal</span></code></td>
<td>LU factorization for Tridiagonal matrices</td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">UmfpackLU</span></code></td>
<td>LU factorization for sparse matrices (computed by UMFPack)</td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">QR</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/QR_decomposition">QR factorization</a></td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">QRCompactWY</span></code></td>
<td>Compact WY form of the QR factorization</td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">QRPivoted</span></code></td>
<td>Pivoted <a class="reference external" href="https://en.wikipedia.org/wiki/QR_decomposition">QR factorization</a></td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">Hessenberg</span></code></td>
<td><a class="reference external" href="http://mathworld.wolfram.com/HessenbergDecomposition.html">Hessenberg decomposition</a></td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">Eigen</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Eigendecomposition_(matrix)">Spectral decomposition</a></td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">SVD</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Singular_value_decomposition">Singular value decomposition</a></td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">GeneralizedSVD</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Generalized_singular_value_decomposition#Higher_order_version">Generalized SVD</a></td>
</tr>
</tbody>
</table></div>
</div>
<div class="section" id="special-matrices">
<h2>Special matrices<a class="headerlink" href="#special-matrices" title="Permalink to this headline">¶</a></h2>
<p><a class="reference external" href="http://www2.imm.dtu.dk/pubdb/views/publication_details.php?id=3274">Matrices with special symmetries and structures</a>
arise often in linear algebra and are frequently associated with
various matrix factorizations.
Julia features a rich collection of special matrix types, which allow for fast
computation with specialized routines that are specially developed for
particular matrix types.</p>
<p>The following tables summarize the types of special matrices that have been
implemented in Julia, as well as whether hooks to various optimized methods
for them in LAPACK are available.</p>
<div class="wy-table-responsive"><table border="1" class="docutils">
<colgroup>
<col width="23%">
<col width="77%">
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">Hermitian</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Hermitian_matrix">Hermitian matrix</a></td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">UpperTriangular</span></code></td>
<td>Upper <a class="reference external" href="https://en.wikipedia.org/wiki/Triangular_matrix">triangular matrix</a></td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">LowerTriangular</span></code></td>
<td>Lower <a class="reference external" href="https://en.wikipedia.org/wiki/Triangular_matrix">triangular matrix</a></td>
</tr>
<tr class="row-even"><td><a class="reference internal" href="../../stdlib/linalg/#Base.Tridiagonal" title="Base.Tridiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">Tridiagonal</span></code></a></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Tridiagonal_matrix">Tridiagonal matrix</a></td>
</tr>
<tr class="row-odd"><td><a class="reference internal" href="../../stdlib/linalg/#Base.SymTridiagonal" title="Base.SymTridiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">SymTridiagonal</span></code></a></td>
<td>Symmetric tridiagonal matrix</td>
</tr>
<tr class="row-even"><td><a class="reference internal" href="../../stdlib/linalg/#Base.Bidiagonal" title="Base.Bidiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">Bidiagonal</span></code></a></td>
<td>Upper/lower <a class="reference external" href="https://en.wikipedia.org/wiki/Bidiagonal_matrix">bidiagonal matrix</a></td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">Diagonal</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Diagonal_matrix">Diagonal matrix</a></td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">UniformScaling</span></code></td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Uniform_scaling">Uniform scaling operator</a></td>
</tr>
</tbody>
</table></div>
<div class="section" id="elementary-operations">
<h3>Elementary operations<a class="headerlink" href="#elementary-operations" title="Permalink to this headline">¶</a></h3>
<div class="wy-table-responsive"><table border="1" class="docutils">
<colgroup>
<col width="29%">
<col width="8%">
<col width="8%">
<col width="8%">
<col width="8%">
<col width="38%">
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">Matrix type</th>
<th class="head"><code class="docutils literal"><span class="pre">+</span></code></th>
<th class="head"><code class="docutils literal"><span class="pre">-</span></code></th>
<th class="head"><code class="docutils literal"><span class="pre">*</span></code></th>
<th class="head"><code class="docutils literal"><span class="pre">\</span></code></th>
<th class="head">Other functions with
optimized methods</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">Hermitian</span></code></td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>MV</td>
<td><a class="reference internal" href="../../stdlib/linalg/#Base.inv" title="Base.inv"><code class="xref jl jl-func docutils literal"><span class="pre">inv()</span></code></a>,
<a class="reference internal" href="../../stdlib/linalg/#Base.sqrtm" title="Base.sqrtm"><code class="xref jl jl-func docutils literal"><span class="pre">sqrtm()</span></code></a>, <a class="reference internal" href="../../stdlib/linalg/#Base.expm" title="Base.expm"><code class="xref jl jl-func docutils literal"><span class="pre">expm()</span></code></a></td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">UpperTriangular</span></code></td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>MV</td>
<td>MV</td>
<td><a class="reference internal" href="../../stdlib/linalg/#Base.inv" title="Base.inv"><code class="xref jl jl-func docutils literal"><span class="pre">inv()</span></code></a>, <a class="reference internal" href="../../stdlib/linalg/#Base.det" title="Base.det"><code class="xref jl jl-func docutils literal"><span class="pre">det()</span></code></a></td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">LowerTriangular</span></code></td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>MV</td>
<td>MV</td>
<td><a class="reference internal" href="../../stdlib/linalg/#Base.inv" title="Base.inv"><code class="xref jl jl-func docutils literal"><span class="pre">inv()</span></code></a>, <a class="reference internal" href="../../stdlib/linalg/#Base.det" title="Base.det"><code class="xref jl jl-func docutils literal"><span class="pre">det()</span></code></a></td>
</tr>
<tr class="row-odd"><td><a class="reference internal" href="../../stdlib/linalg/#Base.SymTridiagonal" title="Base.SymTridiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">SymTridiagonal</span></code></a></td>
<td>M</td>
<td>M</td>
<td>MS</td>
<td>MV</td>
<td><a class="reference internal" href="../../stdlib/linalg/#Base.eigmax" title="Base.eigmax"><code class="xref jl jl-func docutils literal"><span class="pre">eigmax()</span></code></a>, <a class="reference internal" href="../../stdlib/linalg/#Base.eigmin" title="Base.eigmin"><code class="xref jl jl-func docutils literal"><span class="pre">eigmin()</span></code></a></td>
</tr>
<tr class="row-even"><td><a class="reference internal" href="../../stdlib/linalg/#Base.Tridiagonal" title="Base.Tridiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">Tridiagonal</span></code></a></td>
<td>M</td>
<td>M</td>
<td>MS</td>
<td>MV</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><a class="reference internal" href="../../stdlib/linalg/#Base.Bidiagonal" title="Base.Bidiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">Bidiagonal</span></code></a></td>
<td>M</td>
<td>M</td>
<td>MS</td>
<td>MV</td>
<td>&nbsp;</td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">Diagonal</span></code></td>
<td>M</td>
<td>M</td>
<td>MV</td>
<td>MV</td>
<td><a class="reference internal" href="../../stdlib/linalg/#Base.inv" title="Base.inv"><code class="xref jl jl-func docutils literal"><span class="pre">inv()</span></code></a>, <a class="reference internal" href="../../stdlib/linalg/#Base.det" title="Base.det"><code class="xref jl jl-func docutils literal"><span class="pre">det()</span></code></a>,
<a class="reference internal" href="../../stdlib/linalg/#Base.logdet" title="Base.logdet"><code class="xref jl jl-func docutils literal"><span class="pre">logdet()</span></code></a>, <a class="reference internal" href="../../stdlib/math/#Base./" title="Base./"><code class="xref jl jl-func docutils literal"><span class="pre">/()</span></code></a></td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">UniformScaling</span></code></td>
<td>M</td>
<td>M</td>
<td>MVS</td>
<td>MVS</td>
<td><a class="reference internal" href="../../stdlib/math/#Base./" title="Base./"><code class="xref jl jl-func docutils literal"><span class="pre">/()</span></code></a></td>
</tr>
</tbody>
</table></div>
<p>Legend:</p>
<div class="wy-table-responsive"><table border="1" class="docutils">
<colgroup>
<col width="16%">
<col width="84%">
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td>M (matrix)</td>
<td>An optimized method for matrix-matrix operations is available</td>
</tr>
<tr class="row-even"><td>V (vector)</td>
<td>An optimized method for matrix-vector operations is available</td>
</tr>
<tr class="row-odd"><td>S (scalar)</td>
<td>An optimized method for matrix-scalar operations is available</td>
</tr>
</tbody>
</table></div>
</div>
<div class="section" id="id3">
<h3>Matrix factorizations<a class="headerlink" href="#id3" title="Permalink to this headline">¶</a></h3>
<div class="wy-table-responsive"><table border="1" class="docutils">
<colgroup>
<col width="23%">
<col width="7%">
<col width="12%">
<col width="15%">
<col width="15%">
<col width="12%">
<col width="15%">
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">Matrix type</th>
<th class="head">LAPACK</th>
<th class="head"><a class="reference internal" href="../../stdlib/linalg/#Base.eig" title="Base.eig"><code class="xref jl jl-func docutils literal"><span class="pre">eig()</span></code></a></th>
<th class="head"><a class="reference internal" href="../../stdlib/linalg/#Base.eigvals" title="Base.eigvals"><code class="xref jl jl-func docutils literal"><span class="pre">eigvals()</span></code></a></th>
<th class="head"><a class="reference internal" href="../../stdlib/linalg/#Base.eigvecs" title="Base.eigvecs"><code class="xref jl jl-func docutils literal"><span class="pre">eigvecs()</span></code></a></th>
<th class="head"><a class="reference internal" href="../../stdlib/linalg/#Base.svd" title="Base.svd"><code class="xref jl jl-func docutils literal"><span class="pre">svd()</span></code></a></th>
<th class="head"><a class="reference internal" href="../../stdlib/linalg/#Base.svdvals" title="Base.svdvals"><code class="xref jl jl-func docutils literal"><span class="pre">svdvals()</span></code></a></th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">Hermitian</span></code></td>
<td>HE</td>
<td>&nbsp;</td>
<td>ARI</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><code class="xref jl jl-class docutils literal"><span class="pre">UpperTriangular</span></code></td>
<td>TR</td>
<td>A</td>
<td>A</td>
<td>A</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">LowerTriangular</span></code></td>
<td>TR</td>
<td>A</td>
<td>A</td>
<td>A</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><a class="reference internal" href="../../stdlib/linalg/#Base.SymTridiagonal" title="Base.SymTridiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">SymTridiagonal</span></code></a></td>
<td>ST</td>
<td>A</td>
<td>ARI</td>
<td>AV</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
<tr class="row-even"><td><a class="reference internal" href="../../stdlib/linalg/#Base.Tridiagonal" title="Base.Tridiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">Tridiagonal</span></code></a></td>
<td>GT</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
<tr class="row-odd"><td><a class="reference internal" href="../../stdlib/linalg/#Base.Bidiagonal" title="Base.Bidiagonal"><code class="xref jl jl-class docutils literal"><span class="pre">Bidiagonal</span></code></a></td>
<td>BD</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>A</td>
<td>A</td>
</tr>
<tr class="row-even"><td><code class="xref jl jl-class docutils literal"><span class="pre">Diagonal</span></code></td>
<td>DI</td>
<td>&nbsp;</td>
<td>A</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
</tbody>
</table></div>
<p>Legend:</p>
<div class="wy-table-responsive"><table border="1" class="docutils">
<colgroup>
<col width="8%">
<col width="78%">
<col width="14%">
</colgroup>
<tbody valign="top">
<tr class="row-odd"><td>A (all)</td>
<td>An optimized method to find all the characteristic values and/or vectors is available</td>
<td>e.g. <code class="docutils literal"><span class="pre">eigvals(M)</span></code></td>
</tr>
<tr class="row-even"><td>R (range)</td>
<td>An optimized method to find the <code class="docutils literal"><span class="pre">il</span></code><sup>th</sup> through the <code class="docutils literal"><span class="pre">ih</span></code><sup>th</sup> characteristic values are available</td>
<td><code class="docutils literal"><span class="pre">eigvals(M,</span> <span class="pre">il,</span> <span class="pre">ih)</span></code></td>
</tr>
<tr class="row-odd"><td>I (interval)</td>
<td>An optimized method to find the characteristic values in the interval [<code class="docutils literal"><span class="pre">vl</span></code>, <code class="docutils literal"><span class="pre">vh</span></code>] is available</td>
<td><code class="docutils literal"><span class="pre">eigvals(M,</span> <span class="pre">vl,</span> <span class="pre">vh)</span></code></td>
</tr>
<tr class="row-even"><td>V (vectors)</td>
<td>An optimized method to find the characteristic vectors corresponding to the characteristic values <code class="docutils literal"><span class="pre">x=[x1,</span> <span class="pre">x2,...]</span></code> is available</td>
<td><code class="docutils literal"><span class="pre">eigvecs(M,</span> <span class="pre">x)</span></code></td>
</tr>
</tbody>
</table></div>
</div>
<div class="section" id="the-uniform-scaling-operator">
<h3>The uniform scaling operator<a class="headerlink" href="#the-uniform-scaling-operator" title="Permalink to this headline">¶</a></h3>
<p>A <code class="xref jl jl-class docutils literal"><span class="pre">UniformScaling</span></code> operator represents a scalar times the identity operator, <code class="docutils literal"><span class="pre">λ*I</span></code>. The identity operator  <code class="xref jl jl-class docutils literal"><span class="pre">I</span></code> is defined as a constant and is an instance of <code class="xref jl jl-class docutils literal"><span class="pre">UniformScaling</span></code>. The size of these operators are generic and match the other matrix in the binary operations <a class="reference internal" href="../../stdlib/math/#Base.+" title="Base.+"><code class="xref jl jl-obj docutils literal"><span class="pre">+</span></code></a>, <a class="reference internal" href="../../stdlib/math/#Base.-" title="Base.-"><code class="xref jl jl-obj docutils literal"><span class="pre">-</span></code></a>, <a class="reference internal" href="../../stdlib/strings/#Base.*" title="Base.*"><code class="xref jl jl-obj docutils literal"><span class="pre">*</span></code></a> and <a class="reference internal" href="../../stdlib/math/#Base.\" title="Base.\"><code class="xref jl jl-obj docutils literal"><span class="pre">\</span></code></a>. For <code class="docutils literal"><span class="pre">A+I</span></code> and <code class="docutils literal"><span class="pre">A-I</span></code> this means that <code class="docutils literal"><span class="pre">A</span></code> must be square. Multiplication with the identity operator <code class="xref jl jl-class docutils literal"><span class="pre">I</span></code> is a noop (except for checking that the scaling factor is one) and therefore almost without overhead.</p>
</div>
</div>
</div>

In [49]:
I

4-element Array{Int64,1}:
 1
 4
 3
 5

In [50]:
write(STDOUT,"Hello World")

Hello World

11

In [ ]:
read(STDIN,Char)

In [ ]:
a

In [1]:
write(STDOUT,0x61)

a

1

In [2]:
print(STDOUT,0x61)

97

In [4]:
open("hello.txt", "w") do f
    write(f, "Hello")
end

5

In [6]:
open("hello.txt", "r") do f
    uppercase(readall(f))
end

"HELLO"

In [7]:
running = true

true

In [8]:
@async begin
    server = listen(2000)
    while running
       sock = accept(server)
       println("Hello World\n")
     end
end

Task (waiting) @0x0000000082e2b490

In [9]:
connect(2000)

TCPSocket(open, 0 bytes waiting)

Hello World



In [10]:
running = false

false

In [11]:
connect(2000)

TCPSocket(open, 0 bytes waiting)

Hello World



In [12]:
connect(2000)

TCPSocket(open, 0 bytes waiting)

Hello World



In [1]:
listen(ip"127.0.0.1",2000)

Base.TCPServer(active)

In [2]:
@async begin
         server = listen(2001)
         while true
           sock = accept(server)
           @async while isopen(sock)
             write(sock,readline(sock))
           end
         end
       end

Task (waiting) @0x00000000827b7490

In [3]:
clientside=connect(2001)

TCPSocket(open, 0 bytes waiting)

In [4]:
@async while true
          write(STDOUT,readline(clientside))
       end

Task (waiting) @0x00000000827b4010

In [5]:
println(clientside,"Hello World from the Echo Server")

Hello World from the Echo Server


In [6]:
close(clientside)

ERROR (unhandled task failure): ArgumentError: stream is closed or unusable
 in check_open at stream.jl:329


In [7]:
clientside=connect(2001)

TCPSocket(open, 0 bytes waiting)

In [8]:
close(clientside)

ERROR (unhandled task failure): ArgumentError: stream is closed or unusable
 in check_open at stream.jl:329


In [9]:
getaddrinfo("github.com")

ip"192.30.252.131"

In [10]:
r = remotecall(2, rand, 2, 2)

LoadError: LoadError: no process with id 2 exists
while loading In[10], in expression starting on line 1

In [11]:
@doc remotecall

```
remotecall(id, func, args...)
```

Call a function asynchronously on the given arguments on the specified process. Returns a `RemoteRef`.


In [12]:
r = remotecall(1, rand, 2, 2)

RemoteRef{Channel{Any}}(1,1,1)

In [13]:
fetch(r)

2x2 Array{Float64,2}:
 0.0962851  0.575182
 0.317417   0.794743

In [15]:
s = @spawnat 1 1 .+ fetch(r)

RemoteRef{Channel{Any}}(1,1,2)

In [16]:
fetch(s)

2x2 Array{Float64,2}:
 1.09629  1.57518
 1.31742  1.79474

In [17]:
remotecall_fetch(1, getindex, r, 1, 1)

0.09628513808182326

In [18]:
@doc @everywhere

```
@everywhere
```

Execute an expression on all processes. Errors on any of the processes are collected into a `CompositeException` and thrown.


A file can also be preloaded on multiple processes at startup, and a driver script can be used to drive the computation:

```
julia -p <n> -L file1.jl -L file2.jl driver.jl
```

Functions addprocs(), rmprocs(), workers(), and others are available as a programmatic means of adding, removing and querying the processes in a cluster.

In [19]:
@doc addprocs

```
addprocs(machines; keyword_args...) -> List of process identifiers
```

Add processes on remote machines via SSH. Requires julia to be installed in the same location on each node, or to be available via a shared file system.

`machines` is a vector of machine specifications.  Worker are started for each specification.

A machine specification is either a string `machine_spec` or a tuple - `(machine_spec, count)`.

`machine_spec` is a string of the form `[user@]host[:port] [bind_addr[:port]]`. `user` defaults to current user, `port` to the standard ssh port. If `[bind_addr[:port]]` is specified, other workers will connect to this worker at the specified `bind_addr` and `port`.

`count` is the number of workers to be launched on the specified host. If specified as `:auto` it will launch as many workers as the number of cores on the specific host.

Keyword arguments:

  * `tunnel`: if `true` then SSH tunneling will be used to connect to the worker from the             master process. Default is `false`.

  * `sshflags`: specifies additional ssh options, e.g.

```
sshflags=`-i /home/foo/bar.pem`
```

  * `max_parallel`: specifies the maximum number of workers connected to in parallel at a host.                   Defaults to 10.

  * `dir`: specifies the working directory on the workers. Defaults to the host's current          directory (as found by `pwd()`)

  * `exename`: name of the julia executable. Defaults to `"$JULIA_HOME/julia"` or              `"$JULIA_HOME/julia-debug"` as the case may be.

  * `exeflags`: additional flags passed to the worker processes.

  * `topology`: Specifies how the workers connect to each other. Sending a message             between unconnected workers results in an error.

  * `topology=:all_to_all`  :  All processes are connected to each other.                       This is the default.

  * `topology=:master_slave`  :  Only the driver process, i.e. pid 1 connects to the                         workers. The workers do not connect to each other.

  * `topology=:custom`  :  The `launch` method of the cluster manager specifes the                   connection topology via fields `ident` and `connect_idents` in                   `WorkerConfig`. A worker with a cluster manager identity `ident`                   will connect to all workers specified in `connect_idents`.

Environment variables :

If the master process fails to establish a connection with a newly launched worker within 60.0 seconds, the worker treats it a fatal situation and terminates. This timeout can be controlled via environment variable `JULIA_WORKER_TIMEOUT`. The value of `JULIA_WORKER_TIMEOUT` on the master process, specifies the number of seconds a newly launched worker waits for connection establishment.

```rst
..  addprocs(manager::ClusterManager; kwargs...) -> List of process identifiers

Launches worker processes via the specified cluster manager.

For example Beowulf clusters are  supported via a custom cluster manager implemented in package ``ClusterManagers``.

The number of seconds a newly launched worker waits for connection establishment from the master can be
specified via variable ``JULIA_WORKER_TIMEOUT`` in the worker process's environment. Relevant only when using TCP/IP as transport.
```

```rst
..  addprocs(n::Integer; exeflags=``) -> List of process identifiers

Launches workers using the in-built ``LocalManager`` which only launches workers on the local host.
This can be used to take advantage of multiple cores. ``addprocs(4)`` will add 4 processes on the local machine.
```

```rst
..  addprocs() -> List of process identifiers

Equivalent to ``addprocs(CPU_CORES)``

Note that workers do not run a ``.juliarc.jl`` startup script, nor do they synchronize their global state
(such as global variables, new method definitions, and loaded modules) with any of the other running processes.
```


In [20]:
addprocs(CPU_CORES)

4-element Array{Int64,1}:
 2
 3
 4
 5

In [21]:
@doc rmprocs

```
rmprocs(pids...)
```

Removes the specified workers.


In [22]:
rmprocs(2:5)

:ok

In [23]:
@doc workers

```
workers()
```

Returns a list of all worker process identifiers.


In [24]:
workers()

1-element Array{Int64,1}:
 1

In [25]:
addprocs(1)

1-element Array{Int64,1}:
 6

In [27]:
A = rand(1000,1000)
Bref = @spawn A^2
fetch(Bref)

1000x1000 Array{Float64,2}:
 246.404  242.221  238.032  254.706  …  243.282  245.487  252.118  241.057
 243.339  240.513  234.222  250.723     237.769  238.703  250.145  245.079
 250.637  255.786  242.935  257.452     247.73   245.781  262.319  248.367
 243.908  242.856  230.648  255.754     238.263  231.553  254.253  239.455
 244.036  238.761  229.236  251.831     242.485  237.91   247.073  237.546
 254.596  242.011  239.943  253.43   …  243.616  241.755  255.826  245.333
 248.791  243.126  240.897  256.155     237.722  242.708  255.275  243.837
 259.934  249.063  245.371  257.475     248.154  247.738  253.799  251.775
 255.142  257.627  238.962  258.874     247.536  250.887  262.788  250.339
 258.439  246.099  239.835  258.725     246.266  247.585  256.336  250.304
 251.8    249.872  243.343  263.129  …  243.956  246.421  258.376  248.238
 254.33   252.212  244.981  266.164     249.301  247.607  260.646  251.5  
 239.953  238.257  231.743  248.553     234.31   236.973  245.512  242.7

In [28]:
Bref = @spawn rand(1000,1000)^2
fetch(Bref)

1000x1000 Array{Float64,2}:
 251.595  254.33   247.193  252.501  …  248.91   258.599  244.762  247.464
 250.565  248.217  246.03   258.234     247.108  260.579  244.798  255.41 
 260.231  258.129  257.54   261.643     255.022  268.091  253.707  258.482
 261.73   252.601  258.425  259.525     252.993  264.234  246.043  251.129
 250.694  248.909  251.479  258.033     251.815  260.496  246.965  250.312
 254.487  256.475  257.219  258.062  …  252.266  265.012  249.896  251.187
 264.973  262.663  253.166  265.109     258.167  267.081  252.323  259.728
 255.139  255.575  253.545  251.209     248.798  256.714  241.387  243.304
 248.275  248.251  244.467  250.769     244.57   256.027  243.599  244.343
 251.918  254.828  249.018  257.571     251.384  258.705  249.207  251.484
 249.905  250.095  252.897  252.255  …  250.972  261.598  245.073  255.24 
 258.952  258.266  253.873  263.242     260.085  263.137  256.564  255.885
 260.467  259.49   253.134  263.376     254.741  262.654  249.372  255.6

In [29]:
@everywhere function count_heads(n)
    c::Int = 0
    for i=1:n
        c += rand(Bool)
    end
    c
end

In [30]:
a = @spawn count_heads(100000000)
b = @spawn count_heads(100000000)
fetch(a)+fetch(b)

99986694

In [31]:
nheads = @parallel (+) for i=1:200000000
  Int(rand(Bool))
end

99987084

Using “outside” variables in parallel loops is perfectly reasonable if the variables are read-only:

In [33]:
a = randn(1000)
f = (x) -> x + 1
@parallel (+) for i=1:100000
  f(a[rand(1:end)])
end

98074.77751656536

In [34]:
M = Matrix{Float64}[rand(1000,1000) for i=1:10]
pmap(svd, M)

10-element Array{Any,1}:
 (
1000x1000 Array{Float64,2}:
 -0.0315076  -0.00394116   0.0152079    …   0.0559766   -0.0285426 
 -0.0315637  -0.0107547   -0.00628968       0.0284223   -0.0173019 
 -0.0320324  -0.0184949   -0.0250978       -0.0190912    0.00138123
 -0.0314264   0.00468772   0.0325694        0.0037514    0.0455322 
 -0.0320306  -0.0151644   -0.0186629       -0.0225571   -0.0254369 
 -0.0314197   0.0113611   -0.000590949  …  -0.0322469   -0.00495385
 -0.0315449   0.0406572    0.0304707        0.0444839   -0.0188762 
 -0.0319561   0.0423949    2.5135e-5        0.0177694   -0.00352942
 -0.0317524  -0.00495734   0.0261374       -0.037082    -0.0116135 
 -0.0328785  -0.0187632    0.0179927       -0.0138243   -0.0395738 
 -0.0317036  -0.0566868   -0.0353252    …   0.068039    -0.0230809 
 -0.0316762  -0.0128482    0.0308106       -0.0625659    0.0237697 
 -0.0318716  -0.00144806   0.033064        -0.00426291   0.0150939 
  ⋮                                     ⋱                   

In [35]:
@doc pmap

```rst
..  pmap(f, lsts...; err_retry=true, err_stop=false, pids=workers())

Transform collections ``lsts`` by applying ``f`` to each element in parallel.
(Note that ``f`` must be made available to all worker processes; see :ref:`Code Availability and Loading Packages <man-parallel-computing-code-availability>` for details.)
If ``nprocs() > 1``, the calling process will be dedicated to assigning tasks.
All other available processes will be used as parallel workers, or on the processes specified by ``pids``.

If ``err_retry`` is ``true``, it retries a failed application of ``f`` on a different worker.
If ``err_stop`` is ``true``, it takes precedence over the value of ``err_retry`` and ``pmap`` stops execution on the first error.
```


In [36]:
@doc svd

```
svd(A, B) -> U, V, Q, D1, D2, R0
```

Wrapper around `svdfact` extracting all parts the factorization to a tuple. Direct use of `svdfact` is therefore generally more efficient. The function returns the generalized SVD of `A` and `B`, returning `U`, `V`, `Q`, `D1`, `D2`, and `R0` such that `A = U*D1*R0*Q'` and `B = V*D2*R0*Q'`.

```
svd(A, [thin=true]) -> U, S, V
```

Wrapper around `svdfact` extracting all parts the factorization to a tuple. Direct use of `svdfact` is therefore generally more efficient. Computes the SVD of `A`, returning `U`, vector `S`, and `V` such that `A == U*diagm(S)*V'`. If `thin` is `true`, an economy mode decomposition is returned. The default is to produce a thin decomposition.
