In [1]:
import numpy as np

In [2]:
def nn(x, w): return np.sign(np.dot(x, w)).astype(int)

In [3]:
x = np.array([[-2,4,-1], [4,1,-1], [1, 6, -1], [2, 4, -1], [6, 2, -1]])
t = np.array([-1, -1, 1, 1, 1])

In [4]:
n_samples, n_features = x.shape

In [5]:
w = np.zeros(n_features)

In [6]:
w

array([ 0.,  0.,  0.])

In [7]:
nn(x, w)

array([0, 0, 0, 0, 0])

In [8]:
np.sign([0, 10, -11])

array([ 0,  1, -1])

In [9]:
ld = 1 / 1000

In [59]:
def cost(y, t, w, ld): return np.sum(is_misclassified(w, x, t)) + np.sum(ld * w ** 2, 0)

In [50]:
def is_misclassified(w, x, t): return np.fmax(np.sign(1 - np.multiply(t, np.dot(x, w))), 0).reshape(-1,1)

In [62]:
def gradient(w, x, t, ld): 
  return np.sum((ld * 2 * w) - x * t.reshape(-1, 1) * is_misclassified(w, x, t), 0)

In [12]:
def delta_w(w, x, t, learning_rate, ld):
    return learning_rate * gradient(w, x, t, ld)

In [57]:
learning_rate = 0.1; nb_of_iterations = 20

In [64]:
w = np.zeros(n_features)
w_cost = [(w, w, cost(nn(x, w), t, w, ld))]
for i in range(nb_of_iterations):
    w = w - delta_w(w, x, t, learning_rate, ld)
    w_cost.append((w, is_misclassified(w, x, t), delta_w(w, x, t, learning_rate, ld), cost(nn(x, w), t, w, ld)))
w_cost

[(array([ 0.,  0.,  0.]), array([ 0.,  0.,  0.]), 5.0),
 (array([ 0.7,  0.7, -0.1]), array([[ 1.],
         [ 1.],
         [ 0.],
         [ 0.],
         [ 0.]]), array([ 0.2007,  0.5007, -0.2001]), 2.0009899999999998),
 (array([ 0.4993,  0.1993,  0.1001]), array([[ 1.],
         [ 1.],
         [ 0.],
         [ 0.],
         [ 0.]]), array([ 0.2004993,  0.5001993, -0.1998999]), 2.0002990409899999),
 (array([ 0.2988007, -0.3008993,  0.2999999]), array([[ 0.],
         [ 1.],
         [ 1.],
         [ 1.],
         [ 1.]]), array([-0.4997012, -1.1003009,  0.2003   ]), 4.000269822187061),
 (array([ 0.7985019,  0.7994016,  0.0996999]), array([[ 1.],
         [ 1.],
         [ 0.],
         [ 0.],
         [ 0.]]), array([ 0.2007985,  0.5007994, -0.1999003]), 2.0012865882702289),
 (array([ 0.5977034,  0.2986022,  0.2996002]), array([[ 1.],
         [ 1.],
         [ 0.],
         [ 0.],
         [ 0.]]), array([ 0.2005977,  0.5002986, -0.1997004]), 2.0005361729036957),
 (array([ 0.3971

In [37]:
t

array([-1, -1,  1,  1,  1])

In [16]:
nn(x, w)

array([-1, -1, -1, -1, -1])

In [17]:
np.multiply(t, nn(x, w))

array([ 1,  1, -1, -1, -1])

In [18]:
np.fmax(1 - np.multiply(t, nn(x, w)), 0)

array([0, 0, 2, 2, 2])

In [19]:
w

array([-17.76659964, -23.45635126,   5.7893723 ])

In [20]:
w ** 2

array([ 315.65206272,  550.20041431,   33.51683165])

In [21]:
cost(nn(x, w), t, w, ld)

10.496846543409202

In [22]:
np.fmax(np.sign(1 - np.multiply(t, np.dot(x, w))), 0) 

array([ 0.,  0.,  1.,  1.,  1.])

In [23]:
np.sum(np.multiply(t.reshape(-1,1), x), 0)

array([ 7,  7, -1])

In [24]:
t

array([-1, -1,  1,  1,  1])

In [25]:
t.T

array([-1, -1,  1,  1,  1])

In [26]:
t == t.T

array([ True,  True,  True,  True,  True], dtype=bool)

In [27]:
np.sum(np.multiply(t.reshape(-1,1), x) * np.fmax(np.sign(1 - np.multiply(t, np.dot(x, w))), 0).reshape(-1,1), 0) 

array([  9.,  12.,  -3.])

In [28]:
np.sum(np.fmax(1 - np.multiply(t, nn(x, w)), 0).reshape(-1, 1) + np.sum(ld * w ** 2, 0))

10.496846543409202

In [48]:
x, t.reshape(-1, 1), x * t.reshape(-1, 1)

(array([[-2,  4, -1],
        [ 4,  1, -1],
        [ 1,  6, -1],
        [ 2,  4, -1],
        [ 6,  2, -1]]), array([[-1],
        [-1],
        [ 1],
        [ 1],
        [ 1]]), array([[ 2, -4,  1],
        [-4, -1,  1],
        [ 1,  6, -1],
        [ 2,  4, -1],
        [ 6,  2, -1]]))

In [49]:
np.fmax(np.sign(1 - np.multiply(t, np.dot(x, w))), 0).reshape(-1,1)

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])