In [9]:
using PyCall

In [19]:
cd("/Users/utensil/experiments/")

In [13]:
run(`git clone https://github.com/brombo/galgebra.git`)

Cloning into 'galgebra'...


In [20]:
cd("galgebra")

In [14]:
run(`python setup.py install`)

running install
running bdist_egg
running egg_info
creating galgebra.egg-info
writing requirements to galgebra.egg-info/requires.txt
writing galgebra.egg-info/PKG-INFO
writing top-level names to galgebra.egg-info/top_level.txt
writing dependency_links to galgebra.egg-info/dependency_links.txt
writing manifest file 'galgebra.egg-info/SOURCES.txt'
reading manifest file 'galgebra.egg-info/SOURCES.txt'
writing manifest file 'galgebra.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/galgebra
copying galgebra/__init__.py -> build/lib/galgebra
copying galgebra/ga.py -> build/lib/galgebra
copying galgebra/lt.py -> build/lib/galgebra
copying galgebra/metric.py -> build/lib/galgebra
copying galgebra/mv.py -> build/lib/galgebra
copying galgebra/printer.py -> build/lib/galgebra
copying galgebra/setgapth.py -> build/lib/galgebra
creating build/lib/tests
copying tests/__init__

zip_safe flag not set; analyzing archive contents...
galgebra.printer: module MAY be using inspect.getouterframes


removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing galgebra-0.4.0-py2.7.egg
creating /Users/utensil/miniconda2/lib/python2.7/site-packages/galgebra-0.4.0-py2.7.egg
Extracting galgebra-0.4.0-py2.7.egg to /Users/utensil/miniconda2/lib/python2.7/site-packages
Adding galgebra 0.4.0 to easy-install.pth file

Installed /Users/utensil/miniconda2/lib/python2.7/site-packages/galgebra-0.4.0-py2.7.egg
Processing dependencies for galgebra==0.4.0
Searching for numpy==1.9.2
Best match: numpy 1.9.2
Adding numpy 1.9.2 to easy-install.pth file

Using /Users/utensil/miniconda2/lib/python2.7/site-packages
Searching for sympy==1.0
Best match: sympy 1.0
Adding sympy 1.0 to easy-install.pth file

Using /Users/utensil/miniconda2/lib/python2.7/site-packages
Finished processing dependencies for galgebra==0.4.0


In [21]:
run(`python setup.py test`)

running test
running egg_info
writing requirements to galgebra.egg-info/requires.txt
writing galgebra.egg-info/PKG-INFO
writing top-level names to galgebra.egg-info/top_level.txt
writing dependency_links to galgebra.egg-info/dependency_links.txt
reading manifest file 'galgebra.egg-info/SOURCES.txt'
writing manifest file 'galgebra.egg-info/SOURCES.txt'
running build_ext



----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK


In [3]:
basis = "a0 a1 a2 n nbar"

"a0 a1 a2 n nbar"

In [4]:
metric = "# # # 0 0, # # # 0 0, # # # 0 0, 0 0 0 0 2, 0 0 0 2 0"

"# # # 0 0, # # # 0 0, # # # 0 0, 0 0 0 0 2, 0 0 0 2 0"

In [22]:
@pyimport sympy
@pyimport galgebra as ga

In [24]:
coords=sympy.symbols("x,y,z",real=true)
base=ga.Ga("e0 e1 e2",g=[1,1,1],coords=coords)

LoadError: LoadError: UndefVarError: Ga not defined
while loading In[24], in expression starting on line 2

In [25]:
ga

__anon__

In [27]:
inspect.ismodule(ga)

false

See:
* [GAlgebraPrimer.pdf](https://github.com/brombo/galgebra/raw/master/doc/GAlgebraPrimer.pdf)
* [this issue](https://github.com/brombo/galgebra/issues/12)
* [Geometric Algebra For Computer Science, An Object Oriented Approach to Geometry](http://www.geometricalgebra.net/index.html)

In [31]:
cd("/Users/utensil/experiments/")

In [32]:
run(`git clone https://github.com/andrioni/GeoAlg.jl.git`)

Cloning into 'GeoAlg.jl'...


In [33]:
cd("GeoAlg.jl")

In [34]:
include("src/GeoAlg.jl")

LoadError: LoadError: LoadError: TypeError: Metric: in type definition, expected Type{T}, got Tuple{DataType,DataType}
while loading /Users/utensil/experiments/GeoAlg.jl/src/GeoAlg.jl, in expression starting on line 90
while loading In[34], in expression starting on line 1

In [83]:
cd("/Users/utensil/experiments/")

In [84]:
cd("galgebra/galgebra")

In [85]:
filter(readdir(".")) do file_name
    ismatch(r"\.py$", file_name)
end

7-element Array{ByteString,1}:
 "__init__.py"
 "ga.py"      
 "lt.py"      
 "metric.py"  
 "mv.py"      
 "printer.py" 
 "setgapth.py"

In [86]:
@pyimport site

In [87]:
dist_pkgs = site.getsitepackages()[end]

"/Users/utensil/miniconda2/lib/site-python"

In [88]:
mkpath(dist_pkgs)

In [89]:
run(`python setgapth.py`)

#Path of Ga module
/Users/utensil/experiments/galgebra/galgebraos name: posix
site-packages directory: /Users/utensil/miniconda2/lib/site-python/Ga.pth
Ga.pth:
0

Python pth file Ga.pth for all modules of galgebra has been created and
placed in directory appropriate for Linux, Windows, or OSX.  Note that
if Ga.pth already exists the old version will be deleted.



In [96]:
cd("/Users/utensil/experiments/galgebra/examples");readdir(".")

5-element Array{ByteString,1}:
 "LaTeX"     
 "Old Format"
 "Terminal"  
 "ipython"   
 "macdonal"  

In [97]:
cd("Terminal");readdir(".")

11-element Array{ByteString,1}:
 "1d_grad.py"            
 "ConformalConsole.py"   
 "coefs_test.py"         
 "exp_check.py"          
 "lt_check.py"           
 "lt_test.py"            
 "mv_setup_options.py"   
 "prob_not_solenoidal.py"
 "reciprocal.py"         
 "rotations.py"          
 "terminal_check.py"     

In [98]:
run(`python terminal_check.py`)

A = A + A__x*e_x + A__y*e_y + A__z*e_z + A__xy*e_x^e_y + A__xz*e_x^e_z + A__yz*e_y^e_z + A__xyz*e_x^e_y^e_z
A =  A
 + A__x*e_x + A__y*e_y + A__z*e_z
 + A__xy*e_x^e_y + A__xz*e_x^e_z + A__yz*e_y^e_z
 + A__xyz*e_x^e_y^e_z
A =  A
 + A__x*e_x
 + A__y*e_y
 + A__z*e_z
 + A__xy*e_x^e_y
 + A__xz*e_x^e_z
 + A__yz*e_y^e_z
 + A__xyz*e_x^e_y^e_z
g_{ij} =
Matrix([
[(e_x.e_x), (e_x.e_y), (e_x.e_z)],
[(e_x.e_y), (e_y.e_y), (e_y.e_z)],
[(e_x.e_z), (e_y.e_z), (e_z.e_z)]])
X = X__x*e_x + X__y*e_y + X__z*e_z
Y = Y__x*e_x + Y__y*e_y + Y__z*e_z
X*Y =  (e_x.e_x)*X__x*Y__x + (e_x.e_y)*X__x*Y__y + (e_x.e_y)*X__y*Y__x + (e_x.e_z)*X__x*Y__z + (e_x.e_z)*X__z*Y__x + (e_y.e_y)*X__y*Y__y + (e_y.e_z)*X__y*Y__z + (e_y.e_z)*X__z*Y__y + (e_z.e_z)*X__z*Y__z
 + (X__x*Y__y - X__y*Y__x)*e_x^e_y + (X__x*Y__z - X__z*Y__x)*e_x^e_z + (X__y*Y__z - X__z*Y__y)*e_y^e_z
X^Y =  (X__x*Y__y - X__y*Y__x)*e_x^e_y + (X__x*Y__z - X__z*Y__x)*e_x^e_z + (X__y*Y__z - X__z*Y__y)*e_y^e_z
X|Y = (e_x.e_x)*X__x*Y__x + (e_x.e_y)*X__x*Y__y + (e_x.e_

In [50]:
using PyCall
@pyimport sympy
@pyimport ga

sys:1: SymPyDeprecationWarning: 

C, including its class ClassRegistry, has been deprecated since SymPy
1.0. It will be last supported in SymPy version 1.0. Use direct
imports from the defining module instead. See
https://github.com/sympy/sympy/issues/9371 for more info.



In [51]:
g3d = ga.Ga("e*x|y|z")
(ex, ey, ez) = g3d[:mv]()
A = g3d[:mv]("A", "mv")

PyObject A + A__x*e_x + A__y*e_y + A__z*e_z + A__xy*e_x^e_y + A__xz*e_x^e_z + A__yz*e_y^e_z + A__xyz*e_x^e_y^e_z

In [52]:
[display(symbol) for symbol in (ex, ey, ez)]

PyObject e_x

PyObject e_y

PyObject e_z

3-element Array{Any,1}:
 nothing
 nothing
 nothing

In [53]:
X = g3d[:mv]("X", "vector")

PyObject X__x*e_x + X__y*e_y + X__z*e_z

In [54]:
Y = g3d[:mv]("Y", "vector")

PyObject Y__x*e_x + Y__y*e_y + Y__z*e_z

In [55]:
g3d[:g]

PyObject Matrix([
[(e_x.e_x), (e_x.e_y), (e_x.e_z)],
[(e_x.e_y), (e_y.e_y), (e_y.e_z)],
[(e_x.e_z), (e_y.e_z), (e_z.e_z)]])

In [56]:
g3d[:I]()

PyObject e_x^e_y^e_z/sqrt((e_x.e_x)*(e_y.e_y)*(e_z.e_z) - (e_x.e_x)*(e_y.e_z)**2 - (e_x.e_y)**2*(e_z.e_z) + 2*(e_x.e_y)*(e_x.e_z)*(e_y.e_z) - (e_x.e_z)**2*(e_y.e_y))

In [57]:
g3d[:E]()

PyObject e_x^e_y^e_z

In [58]:
mv = g3d[:mv]

PyObject <bound method Ga.mv of <ga.Ga object at 0x317816e90>>

In [59]:
C = mv("C", "scalar")

PyObject C

In [60]:
B = mv("B", "bivector")

PyObject B__xy*e_x^e_y + B__xz*e_x^e_z + B__yz*e_y^e_z

In [61]:
V3 = mv("V3", 3)

PyObject V3__xyz*e_x^e_y^e_z

In [62]:
V2 = mv("V2", 2)

PyObject V2__xy*e_x^e_y + V2__xz*e_x^e_z + V2__yz*e_y^e_z

In [63]:
V1 = mv("V1", 1)

PyObject V1__x*e_x + V1__y*e_y + V1__z*e_z

In [64]:
V0 = mv("V0", 0)

PyObject V0

In [65]:
S = mv("S", "spinor")

PyObject S + S__xy*e_x^e_y + S__xz*e_x^e_z + S__yz*e_y^e_z

In [66]:
I2 = mv("I2", "pseudo")

PyObject I2__xyz*e_x^e_y^e_z

In [67]:
I2 == g3d[:I]()

false

In [68]:
@pyimport operator

See https://docs.python.org/2/library/operator.html#mapping-operators-to-functions

In [69]:
operator.mul(X, Y) # X * Y

PyObject (e_x.e_x)*X__x*Y__x + (e_x.e_y)*X__x*Y__y + (e_x.e_y)*X__y*Y__x + (e_x.e_z)*X__x*Y__z + (e_x.e_z)*X__z*Y__x + (e_y.e_y)*X__y*Y__y + (e_y.e_z)*X__y*Y__z + (e_y.e_z)*X__z*Y__y + (e_z.e_z)*X__z*Y__z + (X__x*Y__y - X__y*Y__x)*e_x^e_y + (X__x*Y__z - X__z*Y__x)*e_x^e_z + (X__y*Y__z - X__z*Y__y)*e_y^e_z

In [70]:
operator.xor(X, Y) # X ^ Y

PyObject (X__x*Y__y - X__y*Y__x)*e_x^e_y + (X__x*Y__z - X__z*Y__x)*e_x^e_z + (X__y*Y__z - X__z*Y__y)*e_y^e_z

In [71]:
operator.or_(X, Y) # X | Y

PyObject (e_x.e_x)*X__x*Y__x + (e_x.e_y)*X__x*Y__y + (e_x.e_y)*X__y*Y__x + (e_x.e_z)*X__x*Y__z + (e_x.e_z)*X__z*Y__x + (e_y.e_y)*X__y*Y__y + (e_y.e_z)*X__y*Y__z + (e_y.e_z)*X__z*Y__y + (e_z.e_z)*X__z*Y__z

In [72]:
operator.lt(X, Y) # X < Y

PyObject (e_x.e_x)*X__x*Y__x + (e_x.e_y)*X__x*Y__y + (e_x.e_y)*X__y*Y__x + (e_x.e_z)*X__x*Y__z + (e_x.e_z)*X__z*Y__x + (e_y.e_y)*X__y*Y__y + (e_y.e_z)*X__y*Y__z + (e_y.e_z)*X__z*Y__y + (e_z.e_z)*X__z*Y__z

In [73]:
operator.add(V0, V1)

PyObject V0 + V1__x*e_x + V1__y*e_y + V1__z*e_z

In [74]:
operator.eq(I2[:norm](), g3d[:I]()[:norm]())

false

In [75]:
operator.sub(I2[:norm](), g3d[:I]())

PyObject Abs(I2__xyz)*sqrt(Abs(-(e_x.e_x)*(e_y.e_y)*(e_z.e_z) + (e_x.e_x)*(e_y.e_z)**2 + (e_x.e_y)**2*(e_z.e_z) - 2*(e_x.e_y)*(e_x.e_z)*(e_y.e_z) + (e_x.e_z)**2*(e_y.e_y))) - e_x^e_y^e_z/sqrt((e_x.e_x)*(e_y.e_y)*(e_z.e_z) - (e_x.e_x)*(e_y.e_z)**2 - (e_x.e_y)**2*(e_z.e_z) + 2*(e_x.e_y)*(e_x.e_z)*(e_y.e_z) - (e_x.e_z)**2*(e_y.e_y))

In [76]:
symbols=sympy.symbols
Ga=ga.Ga
o3d = Ga("e_x e_y e_z", g=[1, 1, 1], coords=symbols("x y z"))

PyObject <ga.Ga object at 0x317810e90>

In [77]:
(ex, ey, ez) = o3d[:mv]()

3-element Array{Any,1}:
 PyObject e_x
 PyObject e_y
 PyObject e_z

In [78]:
[display(e) for e in (ex, ey, ez)]

PyObject e_x

PyObject e_y

PyObject e_z

3-element Array{Any,1}:
 nothing
 nothing
 nothing

In [79]:
o3dmv=o3d[:mv]

PyObject <bound method Ga.mv of <ga.Ga object at 0x317810e90>>

In [80]:
f = o3dmv("f", "scalar", f=true)

PyObject f

In [81]:
A = o3dmv("A", "vector", f=true)

PyObject A__x*e_x + A__y*e_y + A__z*e_z

In [82]:
B = o3dmv("B", "bivector", f=true)

PyObject B__xy*e_x^e_y + B__xz*e_x^e_z + B__yz*e_y^e_z

In [83]:
C = o3dmv("C", "mv", f=true)

PyObject C + C__x*e_x + C__y*e_y + C__z*e_z + C__xy*e_x^e_y + C__xz*e_x^e_z + C__yz*e_y^e_z + C__xyz*e_x^e_y^e_z

In [84]:
grad = o3d[:grad]

PyObject e_x*D{x} + e_y*D{y} + e_z*D{z}

In [85]:
operator.mul(grad, f)

PyObject D{x}f*e_x + D{y}f*e_y + D{z}f*e_z

In [86]:
operator.or_(grad, A)

PyObject D{x}A__x + D{y}A__y + D{z}A__z

In [87]:
operator.mul(grad, A)

PyObject D{x}A__x + D{y}A__y + D{z}A__z + (-D{y}A__x + D{x}A__y)*e_x^e_y + (-D{z}A__x + D{x}A__z)*e_x^e_z + (-D{z}A__y + D{y}A__z)*e_y^e_z

In [88]:
o3d[:E]()

PyObject e_x^e_y^e_z

In [89]:
o3d[:I]()

PyObject e_x^e_y^e_z

In [90]:
o3d[:E]() == o3d[:I]()

true

In [91]:
for op in [operator.mul, operator.xor, operator.or_]
    op_name = op[:__name__]
    display(IJulia.text_markdown,"operator.$op_name(grad, B)=")
    display(op(grad, B))
end

operator.mul(grad, B)=

PyObject (-D{y}B__xy - D{z}B__xz)*e_x + (D{x}B__xy - D{z}B__yz)*e_y + (D{x}B__xz + D{y}B__yz)*e_z + (D{z}B__xy - D{y}B__xz + D{x}B__yz)*e_x^e_y^e_z

operator.xor(grad, B)=

PyObject (D{z}B__xy - D{y}B__xz + D{x}B__yz)*e_x^e_y^e_z

operator.or_(grad, B)=

PyObject (-D{y}B__xy - D{z}B__xz)*e_x + (D{x}B__xy - D{z}B__yz)*e_y + (D{x}B__xz + D{y}B__yz)*e_z

In [92]:
using PyCall
@pyimport ga
@pyimport printer

pyeval("""
Ga('e*x|y|z')
""", Ga=ga.Ga)

PyObject <ga.Ga object at 0x3180677d0>

In [93]:
pyeval("""
A|B
""", A=A, B=B)

PyObject (-A__y*B__xy - A__z*B__xz)*e_x + (A__x*B__xy - A__z*B__yz)*e_y + (A__x*B__xz + A__y*B__yz)*e_z

In [94]:
[display(v) for v in [grad, f, A, B, C]]

PyObject e_x*D{x} + e_y*D{y} + e_z*D{z}

PyObject f

PyObject A__x*e_x + A__y*e_y + A__z*e_z

PyObject B__xy*e_x^e_y + B__xz*e_x^e_z + B__yz*e_y^e_z

PyObject C + C__x*e_x + C__y*e_y + C__z*e_z + C__xy*e_x^e_y + C__xz*e_x^e_z + C__yz*e_y^e_z + C__xyz*e_x^e_y^e_z

5-element Array{Any,1}:
 nothing
 nothing
 nothing
 nothing
 nothing

In [101]:
for expr in ["grad * f",
"grad | A",
"grad * A",
"-o3d.E() * (grad ^ A)",
"grad * B",
"grad ^ B",
"grad | B",
"grad < A",
"grad > A",
"grad < B",
"grad > B",
"grad < C",
"grad > C"]
    display(IJulia.text_markdown, "`$expr` = ")
    display(pyeval(expr, grad=grad, A=A, B=B, C=C, f=f, o3d=o3d))
end

`grad * f` = 

PyObject D{x}f*e_x + D{y}f*e_y + D{z}f*e_z

`grad | A` = 

PyObject D{x}A__x + D{y}A__y + D{z}A__z

`grad * A` = 

PyObject D{x}A__x + D{y}A__y + D{z}A__z + (-D{y}A__x + D{x}A__y)*e_x^e_y + (-D{z}A__x + D{x}A__z)*e_x^e_z + (-D{z}A__y + D{y}A__z)*e_y^e_z

`-o3d.E() * (grad ^ A)` = 

PyObject (-D{z}A__y + D{y}A__z)*e_x + (D{z}A__x - D{x}A__z)*e_y + (-D{y}A__x + D{x}A__y)*e_z

`grad * B` = 

PyObject (-D{y}B__xy - D{z}B__xz)*e_x + (D{x}B__xy - D{z}B__yz)*e_y + (D{x}B__xz + D{y}B__yz)*e_z + (D{z}B__xy - D{y}B__xz + D{x}B__yz)*e_x^e_y^e_z

`grad ^ B` = 

PyObject (D{z}B__xy - D{y}B__xz + D{x}B__yz)*e_x^e_y^e_z

`grad | B` = 

PyObject (-D{y}B__xy - D{z}B__xz)*e_x + (D{x}B__xy - D{z}B__yz)*e_y + (D{x}B__xz + D{y}B__yz)*e_z

`grad < A` = 

PyObject D{x}A__x + D{y}A__y + D{z}A__z

`grad > A` = 

PyObject D{x}A__x + D{y}A__y + D{z}A__z

`grad < B` = 

PyObject (-D{y}B__xy - D{z}B__xz)*e_x + (D{x}B__xy - D{z}B__yz)*e_y + (D{x}B__xz + D{y}B__yz)*e_z

`grad > B` = 

PyObject 0

`grad < C` = 

PyObject D{x}C__x + D{y}C__y + D{z}C__z + (-D{y}C__xy - D{z}C__xz)*e_x + (D{x}C__xy - D{z}C__yz)*e_y + (D{x}C__xz + D{y}C__yz)*e_z + D{z}C__xyz*e_x^e_y - D{y}C__xyz*e_x^e_z + D{x}C__xyz*e_y^e_z

`grad > C` = 

PyObject D{x}C__x + D{y}C__y + D{z}C__z + D{x}C*e_x + D{y}C*e_y + D{z}C*e_z

In [118]:
locals = PyDict(Dict(:grad=>grad, :f=>f))
for expr in ["grad * f"]
    display(IJulia.text_markdown, "`$expr` = ")
    display(PyCall.pyeval_(expr, locals, PyCall.Py_eval_input))
end

`grad * f` = 

PyObject D{x}f*e_x + D{y}f*e_y + D{z}f*e_z

In [119]:
locals = PyDict(Dict(:grad=>grad, :f=>f))
for expr in ["grad * f"]
    display(IJulia.text_markdown, "`$expr` = ")
    display(PyCall.pyeval_(expr, locals, PyCall.Py_single_input))
end

`grad * f` = 

PyObject None

D{x}f*e_x + D{y}f*e_y + D{z}f*e_z


In [120]:
locals = PyDict(Dict(:grad=>grad, :f=>f))
for expr in ["grad * f"]
    display(IJulia.text_markdown, "`$expr` = ")
    display(PyCall.pyeval_(expr, locals, PyCall.Py_file_input))
end

`grad * f` = 

PyObject None

In [122]:
vara = 1;varb = 2;
local_vars = PyDict(Dict(:vara=>vara, :varb=>varb))
PyCall.pyeval_("vara + varb", local_vars, PyCall.Py_single_input)

3


PyObject None

In [123]:
vara = 1;varb = 2;
local_vars = PyDict(Dict(:vara=>vara, :varb=>varb))
PyCall.pyeval_("vara + varb", local_vars, PyCall.Py_eval_input)

PyObject 3

In [124]:
vara = 1;varb = 2;
local_vars = PyDict(Dict(:vara=>vara, :varb=>varb))
PyCall.pyeval_("vara + varb", local_vars, PyCall.Py_file_input)

PyObject None